### ISSUE TITLE
Race condition on PostsView.SCROLL_TYPE_NEW_MESSAGE

### ISSUE THREAD

**Issue by samogot** [mattermost/platform#2735] opened 2016-04-18 06:03 UTC
Some times (often, allways?) channel scrolls to down instead of scrolling to the `New Messages` badge. As i understand it is due race condition between [scrolling](https://github.com/mattermost/platform/blob/master/webapp/components/posts_view.jsx#L318) and [checking](https://github.com/mattermost/platform/blob/master/webapp/components/posts_view.jsx#L89) if we at bottom. That race condition caused by [requestAnimationFrame](https://github.com/mattermost/platform/blob/master/webapp/components/posts_view.jsx#L314) that delays scrolling for some time. I do not sure about how it happens, because i do not investigate call graph between that points, but console.log with stack trace shows that [L89](https://github.com/mattermost/platform/blob/master/webapp/components/posts_view.jsx#L89) executes between [L314](https://github.com/mattermost/platform/blob/master/webapp/components/posts_view.jsx#L314) and [L318](https://github.com/mattermost/platform/blob/master/webapp/components/posts_view.jsx#L318). 
Commenting out [L314](https://github.com/mattermost/platform/blob/master/webapp/components/posts_view.jsx#L314) helps, but it is not the best fix :)

My investigation was on v2.2.0, where is no setTimout on [L314](https://github.com/mattermost/platform/blob/master/webapp/components/posts_view.jsx#L314), but when i try to add this as patch to 2.2.0 - bug still reprodeses

**Comment by hmhealey** [comment] 2016-04-20 20:57
Thanks for the report @samogot. I've noticed the same thing occasionally, but I didn't spend any time looking into the cause.

I'm closing this issue since I've filed a [ticket on Jira] to track it. We'll take a look at this soon, but if you happen to find a good solution to the bug, let us know.

**Closed by hmhealey** 2016-04-20 20:57 UTC
