### ISSUE TITLE
Web/Android - White screen upon loading Mattermost

### ISSUE THREAD

**Issue by irfanitw** [mattermost/platform#4032] opened 2016-09-17 13:26 UTC
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
Sometimes when I load up Mattermost, I see a white screen and a continuous loading gif

#### Steps to reproduce
Hard to say.

#### Expected behavior
Everytime I load up Mattermost, I see Mattermost!

#### Observed behavior
I see a white screen and a continuous loading gif

At this point, I need to clear my cache/cookies on the web and/or clear my application data on the Android app to continue

#### Possible fixes
??

**Comment by jasonblais** [comment] 2016-09-19 04:18
Thanks @irfanitw for the report! 

Can you help answer the following questions to help us with the investigation
 1. Which Mattermost server version are you currently using (from **Main Menu > About Mattermost**)?
 2. Which browser(s) has this occurred?
 3. Does a refresh on the web help resolve the issue, or does it require clearing your cache and cookies?
 4. Have you noticed any particular instances where it has occurred (e.g. when signing into Mattermost, when entering a specific channel or a team, etc.)?

**Comment by irfanitw** [comment] 2016-09-19 21:17
Hi @jasonblais 

Here's the info:

1. MM Server: 3.2, but I've seen this on 3.0 +  3.1
2. Chrome v52
3. Requires clearing cache or cookies. 

I've also noticed I've bookmarked https://<domain>/select_team and so when the issue occurs when I go to this link, I can get by it by going to https://<domain>/

**Comment by jasonblais** [comment] 2016-09-20 05:10
Thanks for the information @irfanitw, very helpful! 

Mattermost server 3.2 and earlier sometimes caused loading issues that required a refresh at minimum (where the page would remain blank until then). This could be related, albeit requiring you to also clear cache/cookies as well.

We did some performance improvements on this in Mattermost v3.3, not sure if you'd be able to access a server v3.3 or later?

We have a [daily built preview instance of Mattermost](pre-release.mattermost.com/core/channels/developers) which is open for everyone to join and currently on v3.4. Would you like to try and see if you're able to reproduce the issue there?

**Comment by irfanitw** [comment] 2016-09-24 18:31
Hi @jasonblais, cool when we upgrade to 3.4 we'll test it out

**Comment by lfbrock** [comment] 2016-10-14 14:12
@irfanitw, just wondering if I can close this issue or if you're still having problems?

**Comment by irfanitw** [comment] 2016-10-14 23:32
@lfbrock, haven't forgotten about this. We're planning to upgrade to MM 3.4 this weekend and then we'll have to wait for 3-4 days to hear back from the iOS users

**Comment by irfanitw** [comment] 2016-10-14 23:32
Uh make that Android users

**Comment by jasonblais** [comment] 2016-10-26 15:23
We haven't received an update so we will assume that the problem is fixed or is no longer valid. 

If the issue persists, reopen this issue with the relevant information.

**Closed by jasonblais** 2016-10-26 15:23 UTC
Labels: Awaiting Submitter Action

**Comment by filipp** [comment] 2017-06-16 11:36
I have the same issue with 3.9 server, 3.7 client on iOS 10.3.2 Force quitting MM doesn't help. Here's a screenshot.
![img_5594](https://user-images.githubusercontent.com/100739/27225061-2ed0e02a-52a1-11e7-9bb0-c28adc7ced46.PNG)

**Comment by cjohannsen81** [comment] 2018-03-13 13:21
@filipp How did you solve this, if at all?

**Comment by filipp** [comment] 2018-03-14 07:41
@cjohannsen81 I think it was fixed with some update. We are currently running 4.7.3 and I haven't seen this issue recently.
