### ISSUE TITLE
Draft Messages Appear in Wrong Channel - v3.5.1

### ISSUE THREAD

**Issue by vrenjith** [mattermost/platform#4924] opened 2017-01-02 12:16 UTC
#### Summary
Draft Messages Appear in Wrong Channel

#### Steps to reproduce
* Type a new message in some channel, leave it as draft and switch to any other window or application
* Wait for a notification message to popup (the browser notification for new messages)
* Click on the notification
* Now the channel for which the notification came will be shown as expected, but now the draft message is now sitting in the edit message box

#### Expected behavior
The draft message should not appear as we have switched channels

#### Observed behavior
The edit box should be blank

#### Possible fixes
No idea.

**Comment by jasonblais** [comment] 2017-01-03 23:05
Thanks @vrenjith for the report,

1) Which browser and OS does this reproduce in? 
2) Does it occur consistently with different messages/users?
3) Does it only occur after clicking a notification, or also in other situations?

**Comment by vrenjith** [comment] 2017-01-04 16:53
* Chrome on Mac
* Consistent
* Found also another way to get this:
 * Type a message in any channel
 * Search for some string in the search window
 * In the side panel of search results, click on `Jump` so that the channel switches to the new one
 * The draft still remains in the edit box

I see this error in the Chrome dev console every time this happens, not sure if this is related
```
Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at a (main.bce07c6….js:43)
    at e.dispatch (main.bce07c6….js:43)
    at e.handleViewAction (main.bce07c6….js:7)
    at Object.S [as l] (main.bce07c6….js:8)
    at t.value (main.bce07c6….js:15)
    at updateComponent (main.bce07c6….js:55)
    at u.receiveComponent (main.bce07c6….js:55)
    at Object.receiveComponent (main.bce07c6….js:10)
    at Object.updateChildren (main.bce07c6….js:54)
    at h._reconcilerUpdateChildren (main.bce07c6….js:56)
    at h._updateChildren (main.bce07c6….js:56)
```

**Comment by jasonblais** [comment] 2017-01-09 05:37
Hey @vrenjith, let me know if you had any further information on the above?

1) Did you click something else after `Jump` on your second set of reproduction steps?
2) At which step do the Chrome console errors appear?

Appreciate your bug reports and for helping improve the quality of Mattermost!

**Comment by vrenjith** [comment] 2017-01-09 05:52
@jasonblais 
I didn't click anywhere else. I can also reproduce the behaviour without notification. I am sending you a video of this.

**Comment by vrenjith** [comment] 2017-01-09 06:05
@jasonblais - https://youtu.be/8_ecyD3GZ3E

**Comment by jasonblais** [comment] 2017-01-09 13:16
@vrenjith helped verify that the issue is resolved on our [public Mattermost community instance](https://pre-release.mattermost.com/core), which is locked for the 3.6 release.

Hence, closing as resolved

**Closed by jasonblais** 2017-01-09 13:16 UTC
Labels: Awaiting Submitter Action
