### ISSUE TITLE
Errbits Slack integration returns a 500

### ISSUE THREAD

**Issue by iGEL** [mattermost/platform#3666] opened 2016-07-25 10:11 UTC
#### Summary
[Errbit](https://github.com/errbit/errbit)s Slack integration doesn't work.

#### Steps to reproduce
We're using Mattermost 3.1 & Errbit 0.6.0. I generated the json body using the rails console of Errbit.

```sh
curl -d '{"username":"Errbit","icon_url":"https://raw.githubusercontent.com/errbit/errbit/master/docs/notifications/slack/errbit.png","attachments":[{"fallback":"[Klaus][development][welcome#index]: RuntimeError http://errbit.example.com/apps/5795cbebdf0f1d0009000000/problems/5795cffadf0f1d0017000007","title":"Hugo","title_link":"http://errbit.example.com/apps/5795cbebdf0f1d0009000000/problems/5795cffadf0f1d0017000007","text":"welcome#index","color":"#D00000","fields":[{"title":"Application","value":"Klaus","short":true},{"title":"Environment","value":"development","short":true},{"title":"Times Occurred","value":1,"short":true},{"title":"First Noticed","value":"2016-07-25 08:38:18","short":true}]}]}' https://[...] -H 'Content-Type: application/json' -v
```

#### Expected behavior
The notification should appear in the correct channel.

#### Observed behavior
Nothing appears in the chat. The logfile only contains the PATH of the webhook, even with log level DEBUG. This is the response from curl:
```
*   Trying [...]...
* Connected to [...] ([...]) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 697 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
[...]
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> POST [...] HTTP/1.1
> Host: [...]
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 699
> 
* upload completely sent off: 699 out of 699 bytes
< HTTP/1.1 500 Internal Server Error
< Server: nginx
< Date: Mon, 25 Jul 2016 09:43:03 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 0
< Connection: keep-alive
< Content-Security-Policy: frame-ancestors 'none'
< X-Frame-Options: DENY
< X-Ratelimit-Limit: 10
< X-Ratelimit-Remaining: 9
< X-Ratelimit-Reset: 1
< X-Request-Id: bfqhoki6jb81uq3rz3y746fbah
< X-Version-Id: 3.1.0.1469439727
< 
* Connection #0 to host [redacted] left intact
```

**Comment by jasonblais** [comment] 2016-08-06 04:05
Really sorry for the significant delay here @iGEL, 

I will confirm with our team and get back to you on this after the weekend

**Comment by enahum** [comment] 2016-08-07 18:15
Hi @iGEL ,

it seems that the problem is the `value` for the `Times Ocurred` field which has an integer value instead of a string, if you convert that value to string, it should work as expected.

Hope this helps.

**Comment by jasonblais** [comment] 2016-08-11 18:49
Closing the issue for now @iGEL , please feel free to re-open if you have further questions

**Closed by jasonblais** 2016-08-11 18:49 UTC
Labels: Awaiting Submitter Action
