### ISSUE TITLE
More Channels modal should not remember the page number when displaying search results

### ISSUE THREAD

**Issue by karlding** [mattermost/platform#7340] opened 2017-09-01 04:02 UTC
#### Summary
The **More Channels** modal should not remember the page number when displaying search results.

#### Steps to reproduce
1. Click the **More...** button under **Public Channels**
2. Ensure that there are enough channels to cause the **Next** button to appear (create additional channels if necessary). Find a channel that isn't on the first page of channels (say **Channel A**)
3. Click **Next** to move to the second page of channels
4. Ensure that you aren't on the first page of channels, and then search for **Channel A**

#### Expected behavior
The expected behaviour is that **Channel A** appears in the first page of search results. There also should only be 1 page of results (if only 1 page matches **Channel A**)

![capture](https://user-images.githubusercontent.com/6836385/29954822-7b361b72-8e8f-11e7-9010-1c066e1f59b7.PNG)

#### Observed behavior (that appears unintentional) 
The modal seems to remember the position at **Step 3**.

![capture](https://user-images.githubusercontent.com/6836385/29954755-fddf989c-8e8e-11e7-83aa-7338a52961d1.PNG)

**Comment by lindy65** [comment] 2017-09-01 06:57
Hello @karlding 

Thank you for your feedback,

Could you tell me what version of Mattermost you're using?  I'm not able to reproduce this on our nightly build server which builds off master so I believe this has already been fixed.

If you'd like to download the latest version, you can do so [here](https://about.mattermost.com/download/).  V4.2 will be released on September 16th.

**Comment by karlding** [comment] 2017-09-01 07:01
I was using the demo server listed in the README. I'm not near a computer to test right now, but I'll take a look later in the week.

**Comment by lindy65** [comment] 2017-09-01 07:16
Sounds good, thanks @karlding 

Let us know how it goes

**Comment by karlding** [comment] 2017-09-01 07:18
I just took a quick look at the Contributors Mattermost listed in the README (which is supposedly running the nightly?), and I'm seeing the same issue using my phone.

To reiterate my steps with a concrete example: 

The only channel listed under **Public Channels** that I've joined is **Reception**

1. Click **More...** under **Public Channels**
2. Click **Next** in the modal to move to the next page of result channels. 
3. Type **kub** and notice the bug (the Previous button shows up, when we expect the Kubernetes channel to show up) 

Note that if you press Previous, you see the expected search result.

**Comment by lindy65** [comment] 2017-09-01 07:29
Hi @karlding 

Apologies, you're quite correct, although I was testing on the nightly build server, I belong to many more channels and was searching different names.  With your example above on the same server, I see the bug and have filed [this ticket](https://mattermost.atlassian.net/browse/PLT-7526) to track.

Thanks!

**Comment by jasonblais** [comment] 2017-09-04 17:35
@karlding We have a help wanted ticket here (https://github.com/mattermost/platform/issues/7344) to see if someone from the community would like to help as well.

Thanks for bringing this to our attention! 👍

**Comment by jasonblais** [comment] 2017-09-04 17:35
Closing for now, we can track via https://github.com/mattermost/platform/issues/7344

**Closed by jasonblais** 2017-09-04 17:35 UTC
