### ISSUE TITLE
Account Settings scroll bug

### ISSUE THREAD

**Issue by leyanlo** [mattermost/platform#5337] opened 2017-02-08 11:25 UTC
#### Summary
Scrolling issue in Account Settings > Advanced

#### Steps to reproduce
1. Go to Account Settings > Advanced
2. Scroll down

#### Expected behavior
Shouldn't be able to scroll down

#### Observed behavior
Scrolls down:
![settings scroll bug](https://cloud.githubusercontent.com/assets/1285326/22735239/bdc562f0-edad-11e6-9983-e1b63cb0925f.gif)

#### Possible fixes
Something to do with ps-scrollbar-y-rail or ps-scrollbar-y:
![screen shot 2017-02-08 at 3 24 32 am](https://cloud.githubusercontent.com/assets/1285326/22735347/2629859c-edae-11e6-9269-e8028536c8bd.png)

**Comment by jasonblais** [comment] 2017-02-08 16:45
Thanks @leyanlo! We have a ticket here to fix it: https://mattermost.atlassian.net/browse/PLT-4066

If anyone is interested helping, please let us know?

**Comment by olku** [comment] 2017-02-10 07:27
I got a similar Problem here.
If we go to Account settings:
Klick on General -> Is ok, Details part is updated
Klick on Security -> Its ok, Details part is updated
Klick in Notifications -> Its ok, Details part is updated
Klick on Display  or Advanced, the App is crashing.

No more updates on the details part or even could we close this window.
 We need to close the whole tab.

Behavior confirmed on 2 PC's  and 2 different  browsers. IE & Chrome.
As well its not working in the Desktop app.
We are running mattermost 3.6.0 on omnibus-gitlab install.

/Nev

**Comment by cinqs** [comment] 2017-02-10 11:26
@olku occured the same problem. waiting for updates

**Comment by lfbrock** [comment] 2017-02-10 19:53
@cinqs - are you on a GitLab omnibus install as well? We're trying to track down the issue, having trouble reproducing on our set up

**Comment by olku** [comment] 2017-02-10 20:01
Yes we are, running omnibus-gitlab 8.16.0.

Is recognized that the problem only exists when you click on the Display part. If you skip, and go to the advanced part its working for advanced as well. Then back to Display, it crashes.

/Olku

**Comment by esethna** [comment] 2017-02-10 20:41
@olku @cinqs We are running an environment with 8.16.2 - which contains Mattermost 3.6.1 - and I was unable to reproduce your issue in Chrome (Mac Sierra & Win10) and IE11 (Win 10). Can you please try to upgrade your instance and let me know if that resolves the issue?

![image](https://cloud.githubusercontent.com/assets/14333569/22843323/4413448c-ef96-11e6-85df-0d541b28c10f.png)

**Comment by cinqs** [comment] 2017-02-11 04:28
Hi, 
I am running on docker with appp of this version [app-prod](https://hub.docker.com/r/mattermost/mattermost-prod-app/)

and the mattermost is not a gitlab onimu...thing, it's version is:

    Version: 3.6.0  (3.6.2)
    Database: postgres

**Comment by jasonblais** [comment] 2017-02-11 05:19
@cinqs Are you also on omnibus-gitlab 3.6.0 install?

I tried with the following reproductions steps on a 3.6.0 Mattermost install, but didn't reproduce:
1) Open Account Settings from the Main Menu
2) Click the General tab
3) Click the Security tab
4) Click the Notifications tab
5) Click the Display tab

--> Observed: No errors given

@olku @cinqs did I miss a step anywhere? This has been reported by a couple of people now so any help is appreciated so that we could resolve this.

PS: @christianAESD this sounds like the same issue you described in #5158. Are you also on omnibus-gitlab 3.6.0 install? Wondering if the issue reproduces only there.

**Comment by jasonblais** [comment] 2017-02-11 05:21
@olku @cinqs @christianAESD

if you'd like to try signing to our public Mattermost community instance and see if the issue reproduces there, that would also be a great help. Team invite link is here if you'd like to try: https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676

**Comment by jasonblais** [comment] 2017-02-11 05:37
Sorry for the first two messages that I since deleted -- for some reason your most recent conversation here didn't show up for me :/

@cinqs @olku 

1) what are your default languages in **System Console > Localization**? If you're using `config.json`, the settings are

```
    "LocalizationSettings": {
        "DefaultServerLocale": ???,
        "DefaultClientLocale": ???,
        "AvailableLocales": ???
    },
```

2) What is your language set in **Account Settings > Display > Language**?
3) What is your default browser language?

[Looks like previously having non-English language settings caused similar JavaScript errors](https://github.com/mattermost/platform/issues/3928#issuecomment-248207289), so this might help us track down the issue.

PS: @christianAESD this sounds like a similar issue to the one you reported in #5158. Would you like to help answer the above three questions to help with our investigation?

**Comment by cinqs** [comment] 2017-02-11 05:42
@jasonblais Ah, exactly. I have Chinese language checked in the System Console as I am a Chinese. 

I just deleted the language selection in the System Console -> localisation. And now everything seems working fine with me. 

And something more, in the localization part, when I checked the languages, any language, the Save button will still be shown as disabled, which mean it gives no feedback and kept grey the color.

the two issues seemed related, huh?

Thanks. you may relate this issue with the ones that problem with System Console with Localization.

**Comment by jasonblais** [comment] 2017-02-11 06:09
Ah, I suspect that's it! 

@olku @christianAESD have you also set `AvailableLocales` to something else than English? I'll create a ticket for this, but it would be great if you were able to confirm it as well.

> something more, in the localization part, when I checked the languages, any language, the Save button will still be shown as disabled, which mean it gives no feedback and kept grey the color.

Yeah, that's a really good point @cinqs. I'll create a separate improvement ticket for it.

**Comment by cinqs** [comment] 2017-02-11 06:41
@jasonblais Oh, I found something more.

Even I don't select any language from the console. From the team user end, I will still be able to choose another language, which means:

I am using a language from the team user end which the language is not *install* as it is designed as so.

**Comment by olku** [comment] 2017-02-11 07:36
OK. We have.:
1.system en
2. Client en
3. Browser german

Available languages 
En,  Fr,  ger,

Greetings olku

**Comment by olku** [comment] 2017-02-11 09:42
So i am going to upgrade vom 

Version: 3.6.0  (3.6.1)
Database: postgres

to.. 
omnibus 8.16.4
 odd, same version of Mattermost
Version: 3.6.0  (3.6.1)
Database: postgres

But now the Bug is gone...

As well the config settings. I have to reconfigure the email and webhook and language stuff again.

Greetings Olku

**Comment by christianAESD** [comment] 2017-02-11 13:02
Deactivating the other locales solved my problem.

**Comment by jasonblais** [comment] 2017-02-15 18:57
Thanks @Nevangalar @cinqs @christianAESD! I created two tickets:

1) [Cannot open Account Settings modal if available languages in config.json doesn't contain the default client language](https://mattermost.atlassian.net/browse/PLT-5548)
2) [Adding feedback when trying to save localization settings in System Console when Available Languages doesn't include the default client language](https://mattermost.atlassian.net/browse/PLT-5549)

Please let us know if any of you are interested helping with a fix?

**Closed by jasonblais** 2017-02-15 18:57 UTC
