### ISSUE TITLE
Page freeze when viewing private messages from a single contact

### ISSUE THREAD

**Issue by orf** [mattermost/platform#3431] opened 2016-06-28 12:36 UTC
#### Summary
After upgrading Gitlab, when I attempt to send a private message to my boss the page becomes unresponsive upon clicking his name. Firefox says that a script is not responding and asks me if I want to debug it, while Chrome offers to kill the tab for me.

#### Steps to reproduce
I'm not sure, it doesn't happen with any other user so I think it may be something to do with the messages that I have exchanged with him. These are obviously sensitive, but I would like to help debug this in any way that I can.

#### Expected behavior
Clicking his name should not cause the page to freeze.

**Comment by lfbrock** [comment] 2016-06-28 13:27
Hi @orf, can you confirm what version of Mattermost you are on? (You should be able to go to the three dot main menu on a team > About Mattermost to see what's there).

**Comment by orf** [comment] 2016-06-29 12:40
Hey, it is version `3.1.0 3.1.0`

**Comment by lfbrock** [comment] 2016-06-29 13:15
@orf, a few more questions:
1. Is there any more details in the Firefox error message?
2. If you have the javascript console open when you click into the channel does it show any errors?
3. Do the Mattermost logs show any errors?
4. Is there anything you know of that's different about that channel compared to others?

**Comment by orf** [comment] 2016-06-29 16:55
Nope, there is nothing in the console at all. The Firefox message just says that the "bundle.js" script is not responding.

There is nothing different about that channel, nothing that I can remember. It's just normal messages with my boss. All I can tell is that it reliably and completely crashes Chrome and Firefox. The tab (and dev tools) become completely unresponsive, to the point where you cant even close the tab. I tried starting a CPU profile, then clicking on my bosses name, but the dev tools doesn't respond when I try to stop the profile.

Is there a way I can get all the messages exchanged with him in JSON (or some other format), then I can filter out sensitive messages and post it here?

**Comment by lfbrock** [comment] 2016-06-29 17:37
@orf - Can you try turning on "Enable Testing" in the System Console, and then go to Account Settings > Advanced > Enable Post Formatting and switch it to "Off"?

Then see if you can access the channel? If that works, then see if there were any posts with formatting in them that could have caused the issue.

**Comment by orf** [comment] 2016-06-29 18:29
Sure, I can try tomorrow and let you know. If it's related to post formatting then I think I might know what it is, I did accidentally send a message to him that had a code snippet that was a single line and incredibly long.

**Comment by orf** [comment] 2016-06-30 09:07
Disabling syntax highlighting fixes the issue. We tracked down the offending message to a single URL that was pasted, which had strange characters in the URL. It was a link to an internal statistics page, so the query being used was in the URL (and it contained lots of punctiation). Unfrtounately the message was deleted and we can't seem to recover it.

**Comment by lfbrock** [comment] 2016-06-30 13:39
Alright thank you @orf! We were able to reproduce the issue and are working on a fix for it. 

We have a ticket tracking the issue, but it's marked as internal because it contains some internal links as well.

**Closed by lfbrock** 2016-06-30 13:39 UTC
