### ISSUE TITLE
Users not created during Slack import

### ISSUE THREAD

**Issue by scbash** [mattermost/platform#1931] opened 2016-01-20 18:52 UTC
Using Mattermost 1.3 or 1.4 I am unable to import users or messages from a Slack export file.  Users are not created, and the following message shows up a lot in the log:
```
[2016/01/06 13:38:03 EST] [WARN] Slack bot posts are not imported yet
```
Which I _assume_ is a side effect of users not being created.  Similarly when running in a development configuration, Mattermost 1.4 prints a lot of variations of:
```
[01/20/16 18:49:56] [DEBG] User: U08K1GKRA does not exist!
```

From the original Slack file I've created [sanitized.zip](https://github.com/mattermost/platform/files/97899/sanitized.zip) which should be free of personal and confidential information.  This file does import successfully into Slack (tested on January 19, 2016).

The [Mattermost forum thread](http://forum.mattermost.org/t/slack-import-fails-in-mattermost-1-3/719?u=sajuka) may have additional details.

**Comment by it33** [comment] 2016-01-21 04:54
Thanks @scbash! @esethna can we have your help seeing if this issue repros on master?

**Comment by kirsty-gasston** [comment] 2016-01-25 15:35
This appears to be a duplicate of #1782

**Comment by Alberts00** [comment] 2016-01-25 18:47
I am experience the same issue.

**Comment by logankaser** [comment] 2016-01-31 20:55
I have the same issue. 
Were only private channels removed from the json? Maybe it is only private channels that are borked?

**Comment by logankaser** [comment] 2016-01-31 20:55
I have the same issue. 
Were only private channels removed from the json? Maybe it is only private channels that are borked?

**Comment by scbash** [comment] 2016-02-02 12:15
@logankaser My Slack export file only includes public channels (I didn't think Slack supports exporting private channels?).

**Comment by logankaser** [comment] 2016-02-02 16:03
@scbash You are right, so that can't be it.

**Comment by vcazan** [comment] 2016-02-03 14:44
I'm having the same issue with 1.4. Log states that channels where merged but in fact no data has been imported, channels are created but users are not. Waiting in a fix for this and we will be transitioning off slack.

**Comment by esethna** [comment] 2016-02-05 19:02
Hi all, our team was able to repro, sharing the [JIRA ticket](https://mattermost.atlassian.net/browse/PLT-1781) to fix this issue.

**Closed** 2016-02-05 19:05 UTC
Labels: Can anyone from community repro this?
