### ISSUE TITLE
Incoming webhooks seems to be incompatible with GitHub (or GitLab or GitBucket) webhooks

### ISSUE THREAD

**Issue by iwaseyusuke** [mattermost/platform#2017] opened 2016-01-29 08:22 UTC
Hi,

I'm trying to integrate GitHub push events by using Incoming webhooks.
But, unfortunately, I had no luck.

From source code (platform/web/web.go), incoming webhooks requires "text" field in webhook payload,
OTOH, GitHub PushEvent, which described here:
https://developer.github.com/v3/activity/events/types/#pushevent
does not have "text" field.
So, Mattermost replies the following error message to GitHub.
<pre>
[EROR] /hooks/xxx-key-xxx code=500 ... No text specified [details: ]
</pre>

Does Incoming webhooks not support GitHub (or GitLab or GitBucket) webhooks yet?
or
Do you have any plan to support this?

Thanks

**Comment by it33** [comment] 2016-01-31 23:46
GitLab notifications to Mattermost via the Slack UI are confirmed to work and [documentation for setup is available](https://gitlab.com/gitlab-org/omnibus-gitlab/tree/master/doc/gitlab-mattermost#setting-up-mattermost-as-a-slack-project-service-integration). 

The GitHub payload looks pretty different. 

There are multiple integrations for [GitHub and Mattermost](https://github.com/softdevteam/mattermost-github-integration) and each formats the Mattermost post differently. 

Would anyone be interested in making a PR to better support GitHub for Mattermost's incoming webhooks? 

For now the extra handling could be hardcoded, eventually we'd probably want to expose some sort of plug-in format to add more of these.

**Comment by iwaseyusuke** [comment] 2016-02-01 04:59
Thanks for your reply!
My workaround was very similar to the softdevteam/mattermost-github-integration,
but this project seems to be more powerful than mine. I'll try it.

Slack - GitHub integration is very popular, so many user needs this feature, I think.
I wish that Mattermost's incoming webhooks support GitHub's raw webhook.

Thanks

**Comment by it33** [comment] 2016-02-04 17:33
It's an interesting idea, to interpret the payload of a generic webhook we'd probably need to create a "type" system for webhooks. 

Would anyone in the community be interested in working on this?

**Comment by iwaseyusuke** [comment] 2016-02-04 23:46
FYI,
I found [hubot-mattermost](https://www.npmjs.com/package/hubot-mattermost) is another altenative to integrate mattermost) and GitHub (GitBucket/GitLab)
e.g.) GitHub --(webhooks)--> Hubot --(hubot-mattermost)--> Mattermost
Now, I'm trying this.

**Comment by it33** [comment] 2016-02-21 04:54
Thanks @iwaseyusuke, closing this ticket since the original issue seems to be answered,

**Closed by it33** 2016-02-21 04:54 UTC
Labels: Needs Jira ticket

**Comment by haikuoyao** [comment] 2017-02-28 07:31
I'm on the same boat with you. Did anyone have a solution for this ?
