### ISSUE TITLE
Notification jingle loudness and visual cues in native app (android).

### ISSUE THREAD

**Issue by killua-eu** [mattermost/platform#4078] opened 2016-09-22 21:46 UTC
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 
#### Summary

Android client plays ultra low volume sound on push notification, doesn't show a visual information (i.e. in the notification drawer).
#### Steps to reproduce
- Mattermost platform 3.4 with relevant configuration as follows

```
    "SendPushNotifications": true,
    "PushNotificationServer": "https://push-test.mattermost.com",
    "PushNotificationContents": "generic",
    "EnableEmailBatching": true,
    "EmailBatchingBufferSize": 256,
    "EmailBatchingInterval": 30
```
- Android app 3.4.1, problem present on several different models, i.e.
  - LG G3, with latest Cyanogenmod 13
  - Samsung Galaxy S5neo Android 6.0.1
#### Expected behavior
- Visual que on incoming messages (a notification drawer entry, a counter over the desktop shortcut icon)
- Normal volume of jingle played on incoming message.
#### Observed behavior
- On all tested phones, I had to put the phone's speaker right next to my ear and ramp up the volume to max to hear something.

**Comment by jasonblais** [comment] 2016-09-27 12:55
Thanks for the report @killua-eu,

We reproduced the bug with a faint sound and I've [created an issue in Jira](https://mattermost.atlassian.net/browse/PLT-4306) for us to track.

During testing, the notifications seem to appear in the notifications drawer for us. Can you help check the Mattermost notification settings on your phone have enabled these entries?

**Comment by krisak** [comment] 2016-09-27 13:07
I can reproduce on OnePlus One (CyanogenOS).

No notifications in drawer. I can hear faint sound if app is in foreground. No sound if app is in background. There is visual notification when i come to the app (red number top left).

As far as i can see there is no notification or anything if app is not open.

**Comment by killua-eu** [comment] 2016-09-27 17:22
Hi @jasonblais , not at all, thanks for working on resolving the issue. I'm unaware of any special settings of the client with respect to visual notifications -  the only relevant i can see is:

⋮ -> account settings -> notifications -> mobile push notifications -> for all activity when online away or offline

But if this were unset, I guess I shouldn't even hear the supersilent "ding". If there's some other setting I'm not aware of, please let me know how I can navigate to it. If there's sthing else you need to reproduce, please let me know as well.

**Comment by jasonblais** [comment] 2016-09-29 20:31
Thank you once more @killua-eu and @krisak for the report,

We've reproduced the issue after re-installing the Android app -- I've created a ticket [in Jira for us to track](https://mattermost.atlassian.net/browse/PLT-4321).

If anyone is interested in helping submit a fix, please let us know!

**Comment by jasonblais** [comment] 2016-10-18 04:22
Hey @killua-eu and @krisak 

We re-installed the Android app v3.4 and weren't able to reproduce the problem anymore (notification shows on the drawer + sound plays as normal).

Wondering if either of you would like to try re-installing the latest Mattermost Android app from Google Play store?

As above, please make sure push notifications are enabled in **Account Settings > Notifications > Mobile push notifications** such as in the screenshot attached

![image](https://cloud.githubusercontent.com/assets/13119842/19464283/f584172e-94c8-11e6-9b80-e30f9147c50c.png)

**Comment by killua-eu** [comment] 2016-10-18 07:25
Hi, reinstalled Mattermost from Google play and configured the Mobile push notifications according to the screenshot. Unfortunately I can still reproduce the problem:

1. with system volume set to max, i can barely hear the jingle.
2. i still don't get any notifications in the system notification drawer, so when I overhear the jingle, I have no way of finding out about a new message except for opening the app and looking at the counter in the app.

What I also noticed, is that changing **send mobile push notifications** to the value "for all activity" doesn't really send notifications for all activity, only for @ mentions. I'd assume these problems can be related.

**Comment by killua-eu** [comment] 2016-10-18 07:34
Update: I noticed, that changing  send mobile push notifications to the value "for all activity" actually doesnt emit notification jingles on all activity, but on only on the first @ mention. until I read the incoming messages, I won't get to "hear about" any new messasge/mention at all (at least not when its a direct message with a @ mention from the same person over and over again). If I change the settings to "for mentions and direct messages", @ mentions will always trigger the sound.

**Comment by killua-eu** [comment] 2016-10-18 08:58
Update2: I noticed there's a separate system setting for notification sounds. Ramping up the volume there make's the mattermost notification jingle kinda audiable at the cost of having all other notification sound volumes extremely high.

**Comment by jasonblais** [comment] 2016-10-20 15:54
@esethna Can you help investigate what might be causing the issues here?

**Comment by esethna** [comment] 2016-10-20 20:43
Thanks for the report, I will check with other members of our team with Android devices to attempt to repro again. We've had a few reports push notification issues on Android 6.0.1. @killua-eu, just to confirm, this is the OS you're using?

**Comment by killua-eu** [comment] 2016-10-26 11:21
@esethna , sorry for the late reply, yes my current Cyanogen version has android 6.0.1

**Comment by esethna** [comment] 2016-11-01 16:28
Hi @killua-eu , can you please also try the following steps:

1. Verify a sound has been selected for push notifications. Go to Settings → Sound & Notification → Default Notification Ringtone and select a sound. 
2. Make sure the app is set as a prioritized app in priority mode in device settings.
3. Check to see if the app is being silenced by Doze mode in device settings. Check to see if any other volume-manipulating apps are running.

**Comment by krisak** [comment] 2016-11-01 18:47
I think the problem must be with our server setup. Again we dont even get the push notifications. (I am on same server as @killua-eu). Is there some public test instance running so i can test the client? I couldnt find any.

**Comment by esethna** [comment] 2016-11-01 19:25
Feel free to join our pre-release contributors team and use the public test channel:

https://pre-release.mattermost.com/core/channels/public-test-channel

**Comment by jasonblais** [comment] 2016-11-14 14:33
Hey @krisak, did you get a chance to test it out on our [preview Mattermost instance](https://pre-release.mattermost.com/core/channels/public-test-channel)?

**Comment by krisak** [comment] 2016-11-14 20:47
Sorry, i just did. Nothing. I was totaly sure it is our server but its not. Same thing on pre-release.mattermost. 

Is it possible that its because of our OS? The only corelation is that both me and @killua-eu have cyanogenmod not pure google android. I have google services allowed though and ive never had any problem with push notifs.

**Comment by esethna** [comment] 2016-11-17 17:36
@krisak @killua-eu we've updated the Play Store app for v3.5 after being able to repro some of these push notifications issues. Please update and try again? Hopefully your issues should be solved.

**Comment by killua-eu** [comment] 2016-11-19 23:45
@esethna sorry for my late reply, I was out of reach. 3.5 resolves the problem for me, I hope that for @krisak as well. I'm suggesting to close this issue as resolved.

**Comment by krisak** [comment] 2016-11-20 10:30
There is no preview of the notification message in tray and when you go to the mattermost app using the notification you wont apear in the right channel where the notification comes from (it puts you to the last visited channel). But at least the notifications seem to work.

**Comment by esethna** [comment] 2016-11-21 16:46
@krisak in the system console there is the setting for choosing if message contents display in the push notifications. Maybe try toggling this settings?
![image](https://cloud.githubusercontent.com/assets/14333569/20491587/18eb213c-afcf-11e6-8c3c-3f3d73e59db5.png)

In terms of getting notifications to take you to the corresponding channel, we have an improvement [ticket](https://mattermost.atlassian.net/browse/PLT-1549) for this.

**Comment by krisak** [comment] 2016-11-24 10:20
Ok, i get why there is nothing now. Makes sense, thx.

**Comment by lfbrock** [comment] 2016-11-24 19:39
Going to close this issue now, and will track the improvement to make push notifications go to the channel here: https://mattermost.atlassian.net/browse/PLT-1549

**Closed by lfbrock** 2016-11-24 19:39 UTC
Labels: Awaiting Submitter Action
