### ISSUE TITLE
Mattermost in Docker = blank page in Safari

### ISSUE THREAD

**Issue by Yzord** [mattermost/platform#2513] opened 2016-03-23 15:07 UTC
I have running Mattermost with Docker and everything is working fine in Firefox, but Safari gives me a blank page. 

http://89.248.166.90

Anyone an idea?

**Comment by lfbrock** [comment] 2016-03-23 15:21
Hi @Yzord, if you're running off of master I think this was caused by this bug: https://mattermost.atlassian.net/browse/PLT-2378

Looks like a fix went in for it recently.

**Comment by Yzord** [comment] 2016-03-23 15:25
This issue can't be viewed

The issue you're trying to view can't be displayed.
It may have been deleted or you don't have permission to view it right now

**Comment by lfbrock** [comment] 2016-03-23 16:34
Hi @Yzord, sorry fixed the permissions on that image. I think you're on a daily build - the v2.1.0 release should have a build date of Mar 14. 

Master is a little unstable right now, we added some larger changes and are currently fixing a few bugs that were introduced.

**Comment by Yzord** [comment] 2016-03-24 13:19
This is what i have in my yml file

> mattermost:
  image: mattermost/platform
  ports:
    - 80:80
  restart: always

**Comment by lfbrock** [comment] 2016-03-28 13:30
Hi @Yzord, this issue should be fixed on master, you should be able to see the fix if you use mattermost/platform:dev.

**Closed by lfbrock** 2016-03-28 13:30 UTC

**Comment by henningkessler** [comment] 2016-04-01 17:11
Hello, 
I just did a test with the latest docker image (mattermost/platform:latest) and had the same experience...
what am I doing wrong
