### ISSUE TITLE
[Help Wanted] [PLT-6295] View Info modal on old mobile app doesn't scroll

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6063] opened 2017-04-10 16:08 UTC
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6295)

Repro steps:
1) Log into Mattermost on the old mobile app
2) Create a channel with a header containing the maximum number of characters (or at least a lot of short lines of text)
3) Tap the header and select View Info

Observed: The header fills up most of the screen and you can't scroll down to view the channel ID
Expected: You should be able to scroll when the content overflows the screen

**Comment by lfbrock** [comment] 2017-06-16 16:20
duplicate of https://github.com/mattermost/platform/issues/6084

**Closed** 2017-06-16 16:19 UTC
Labels: Difficulty: Introductory, ReactJS
