### ISSUE TITLE
Changing primary email address in Gitlab breaks Mattermost integration

### ISSUE THREAD

**Issue by drf** [mattermost/platform#1879] opened 2016-01-13 11:43 UTC
Scenario: User is registered to Mattermost through Gitlab SSO

* User changes primary email in Gitlab
* Mattermost does not recognise the account anymore

Apparently users are indexed by primary mail, and in case this changes the SSO breaks.

**Comment by lfbrock** [comment] 2016-01-14 18:02
Hi @drf, 

I tried to repro this but it seemed to work for me, I go to GitLab > Profile Settings and change the "Email" field. I confirm the email, and then if I try to log in to Mattermost using GitLab SSO everything seems to work fine. 

I'm testing on v1.4, so it's possible the issue was fixed in the latest version. You can test v1.4 on our gitlab.mattermost.com site, or the final version will be released soon. Can you let me know if the issue is fixed on 1.4, or if there's anything else I should try to repro the issue?

**Comment by it33** [comment] 2016-02-21 04:30
Closing as no repro, @drf please re-open or create a new issue if you still see the issue?

**Closed by it33** 2016-02-21 04:30 UTC
Labels: Awaiting Submitter Response
