### ISSUE TITLE
We couldn't save the channel

### ISSUE THREAD

**Issue by dansto** [mattermost/platform#6590] opened 2017-06-06 08:29 UTC
Reopening Direct Messages  with more than one users does't work;

Version:  mattermost-3.9.0-linux-amd64.tar.gz

* Open Direct Messages  with 3 users
* Close that chat with (by clicking on "X" (Remove from List))
* Try to open Direct Messages with same 3 users does not work.

When clicking on button "Go" following error appears in JavaScript Console

method=createGroupChannel msg=We couldn't save the channel detail= rid=ja8myj4zfjff3qwn14xj6m7maa

**Comment by lindy65** [comment] 2017-06-07 07:34
Hi @dansto,

Could you tell me which version of Mattermost you are using?

I am not able to repro your issue on master with the example you gave.

**Comment by dansto** [comment] 2017-06-07 07:41
mattermost-3.9.0-linux-amd64 Enterprise edition....in free mode (without subscription)

**Comment by lindy65** [comment] 2017-06-08 08:13
Thanks @dansto,

It seems this issue is fixed on master.  Perhaps we could have your help upgrading to v3.10 which will release on June 16th to see if the issue still exists for you?

**Comment by dansto** [comment] 2017-06-08 08:15
ok we will upgrade on June 16th...thx

**Comment by lindy65** [comment] 2017-06-14 11:48
I'll close this issue off for now @dansto 

Feel free to reopen it if you still experience problems after your upgrade.

**Comment by dansto** [comment] 2017-06-16 07:55
after Upgrade we still get the same error.

We are using PostgreSQL 9.5

Here ist the Postgres error log:

2017-06-16 09:49:46.055 CEST [31182] mmuser@mattermost ANWEISUNG:  insert into "channels" ("id","createat","updateat","deleteat","teamid","type","displayname","name","header","purpose","lastpostat","totalmsgcount","extraupdateat","creatorid") values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14);
2017-06-16 09:49:59.148 CEST [31170] mmuser@mattermost FEHLER:  doppelter Schlüsselwert verletzt Unique-Constraint »channels_name_teamid_key«
2017-06-16 09:49:59.148 CEST [31170] mmuser@mattermost DETAIL:  Schlüssel »(name, teamid)=(153e4528fa321c15004173e7d3444b837ed6bbe9, )« existiert bereits.

**Comment by dansto** [comment] 2017-06-16 08:38
@lindy65 could you reopen #6590 ?

**Comment by lindy65** [comment] 2017-06-16 09:29
Sure, @dansto :)

Are you still experiencing this issue after upgrading to Mattermost 3.10?  

I am still not able to repro your issue on our postgres instance (even without an enterprise licence) so I'll ask one of our devs if they can assist.  Perhaps it has something to do with Postgres database?

**Comment by dansto** [comment] 2017-06-16 10:05
yes still after upgrade

as a workarround we can use the new function "switch channels ctrl-k"

**Comment by lfbrock** [comment] 2017-06-16 14:21
Hi @dansto - does this happen for all group messages you try to re-open, or only for specific ones?

**Comment by dansto** [comment] 2017-06-19 07:53
yes for all group messages with more than 2 users....

**Comment by jasonblais** [comment] 2017-06-26 12:27
@dansto Thanks for the report, 

1) Did the feature work until some point and then start to fail last month?
2) Do you see any errors in the JavaScript console? [Instructions here how to access it](http://stackoverflow.com/questions/66420/how-do-you-launch-the-javascript-debugger-in-google-chrome) -- if you do, please share a screenshot?
3) Does this reproduce for all users at your Mattermost server?
4) Which browser (or desktop app) does this reproduce? Does it reproduce on more than browser (ex: Chrome and Firefox)

**Comment by dansto** [comment] 2017-06-26 12:59
1. no
2. https://www.screencast.com/t/nrfrpWiPCpJ
3. Yes
4. Chrome and Desktop App. Firefox we dont use.

Postgresql log:

2017-06-26 14:55:21.154 CEST [554] mmuser@mattermost FEHLER:  doppelter SchlÃŒsselwert verletzt Unique-Constraint Â»channels_name_teamid_keyÂ«
2017-06-26 14:55:21.154 CEST [554] mmuser@mattermost DETAIL:  SchlÃŒssel Â»(name, teamid)=(153e4528fa321c15004173e7d3444b837ed6bbe9, )Â« existiert bereits.
2017-06-26 14:55:21.154 CEST [554] mmuser@mattermost ANWEISUNG:  insert into "channels" ("id","createat","updateat","deleteat","teamid","type","displayname","name","header","purpose","lastpostat","totalmsgcount","extraupdateat","creatorid") values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14);

**Comment by jasonblais** [comment] 2017-06-28 19:07
Thanks @dansto, 

Just a couple of more questions:

1) Are you using local, Docker or GitLab omnibus for your Mattermost deployment?
2) If local, which server OS and database version are you using? 
3) Is the database server used exclusively for Mattermost or is it also used for something else?

**Comment by dansto** [comment] 2017-06-29 07:48
1. local
2. debian stretch, postgresql 9.5
3. also for something else

**Comment by sousapro** [comment] 2017-07-19 23:14
hey dansto,

I've been looking into this issue as well and been unable to reproduce it in several VMs. I'm leaning towards the shared database being an issue. Is there any chance that permissions have been changed on the mattermost database by the other applications/users on the postgres database server?

**Comment by dansto** [comment] 2017-07-20 08:23
dont't think so.

Maybe I can create a VM and send it to you ?

**Comment by lindy65** [comment] 2017-07-26 08:38
Hi @dansto,

v4.0.1 was recently released.  Could you try upgrading to see whether this helps?  You can download the latest version [here](https://about.mattermost.com/download/).

**Comment by dansto** [comment] 2017-07-26 08:47
ok we will try...

**Comment by lindy65** [comment] 2017-07-26 17:02
Thanks @dantso!  Let us know how it goes :)

**Comment by dansto** [comment] 2017-07-27 09:02
still same error:

[2017/07/27 11:01:36 CEST] [EROR] /api/v4/channels/group:SqlChannelStore.Save code=500 rid=3r1a1kohefdzbbt6ekt5neiaxr uid=9t9happfcbbazehsutosaxeedy ip=87.191.51.26 We couldn't save the channel [details: id=4fr8fmwjnp8e9jrkg6twwopaey, pq: doppelter SchlÃŒsselwert verletzt Unique-Constraint Â»channels_name_teamid_keyÂ«]


should we create a VM and send it to you ?

**Comment by lindy65** [comment] 2017-07-27 19:00
Yes, thanks @dansto, I believe @sousapro was going to take a look at the VM once we heard back how it had gone after you upgraded.

**Comment by sousapro** [comment] 2017-07-28 00:51
How would you like to share your VM? Also, is there any way to get your database on its own postgresql instance

**Comment by dansto** [comment] 2017-07-28 07:20
hi....maybe via dockerhub ?

**Comment by dansto** [comment] 2017-07-28 13:32
When trying to build the VM I found out that it has something to do with locale.
With english locale it's working.

With locale de_DE.UTF-8 it's not working.
We have set linux locale and postgres locale to de_DE.UTF-8.

Can you reproduce/fix that?

**Comment by sousapro** [comment] 2017-07-28 17:00
@dansto, would you mind installing this into your test VM? https://releases.mattermost.com/4.0.2-rc1/mattermost-4.0.2-rc1-linux-amd64.tar.gz (or if you are using team edition https://releases.mattermost.com/4.0.2-rc1/mattermost-team-4.0.2-rc1-linux-amd64.tar.gz). This has a fix in it for some locale issues and I believe it might resolve your issue. Thank you for you patience in getting this fixed

Sousapro

**Comment by dansto** [comment] 2017-07-31 09:03
it also doesnt work with this version

but if I change in postgresql.conf  lc_messages = 'de_DE.UTF-8'   to lc_messages = 'en_US.UTF-8'  then it works. Also in Production Environment.

Seems like you are matching against postgresl error messages?

**Comment by lindy65** [comment] 2017-08-27 17:30
Hi @dansto,

Apologies for the delay in getting back to you.  There has been some discussion about your issue and we've created a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7493) to fix.

Thanks again for the report!  I'll close this off here for now and we can track via Jira.

**Closed by lindy65** 2017-08-27 17:30 UTC

**Comment by jasonblais** [comment] 2017-09-08 19:06
@dansto @sousapro @prixone Just a heads up that this issue will be fixed in Mattermost v4.3, released in October 16th.

I realize it's an inconvenience @dansto but the fix was too close to the v4.2 release date for us to take it, given the database changes involved.
