### ISSUE TITLE
Regression: The system admin cannot update team name, error "You do not have the appropriate permissions"

### ISSUE THREAD

**Issue by chengweiv5** [mattermost/platform#868] opened 2015-09-30 01:38 UTC
I created a team with gitlab 7.9.2 oauth and then trying to update the team name like below, however, it failed.

![mm-team-update](https://cloud.githubusercontent.com/assets/689798/10182447/d79ddeac-6756-11e5-8a66-a03beeae9997.png)

**Comment by it33** [comment] 2015-09-30 02:19
Thanks @chengweiv5, nice find! Looks like a regression we need to fix.

**Comment by coreyhulen** [comment] 2015-09-30 02:32
I think this is the same issue as https://mattermost.atlassian.net/browse/PLT-461.  If you're system_admin then you cannot rename the team, but if your just admin (ie the team admin) then it will succeed.

**Comment by it33** [comment] 2015-09-30 08:07
Hi @chengweiv5, if you create a second account and give it "Team Admin" permissions, are you able to rename the team?

**Comment by coreyhulen** [comment] 2015-10-01 04:23
Fixed with https://github.com/mattermost/platform/pull/884

**Closed by coreyhulen** 2015-10-01 04:23 UTC
