### ISSUE TITLE
CORS Access-Control-Expose-Headers

### ISSUE THREAD

**Issue by federicolucca** [mattermost/platform#6159] opened 2017-04-19 14:14 UTC
Hi,

I trying to create a chat for some website, based on a single mattermost api host.
When i call the login i see the token but the angular2 response hides the headers because they are not allowed in cross origin call.

There is a way to "solve" ?

Thanks
Federico

**Comment by enahum** [comment] 2017-04-21 13:34
Hi @federicolucca you have a system console configuration to set the Cross origin requests
![image](https://cloud.githubusercontent.com/assets/6757047/25279804/0ba8fc3a-267e-11e7-809e-070b5a8c74c0.png)

**Comment by lindy65** [comment] 2017-05-03 09:57
Hi @federicolucca, 

Just circling back to see whether you have managed to resolve your issue?

**Comment by ibigpapa** [comment] 2017-05-03 20:32
Hi I Have the same issue my setting have Enable CORS set to `*`
i have enable insecure outgoing connections also enabled.

**Comment by ibigpapa** [comment] 2017-05-03 20:35
I think the crux of the issue is related to the fact the Preflight response `Access-Control-Allow-Headers` set to only allow `content-type` header.  Which i'm able to successfully fetch that header in the `response.headers.get('content-type')`.  
```
HTTP/1.1 200 OK
Access-Control-Allow-Headers: content-type
Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, PATCH, DELETE
Access-Control-Allow-Origin: http://127.0.0.1:3000
Date: Wed, 03 May 2017 20:22:39 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8
111

**Comment by ibigpapa** [comment] 2017-05-03 21:01
Recreated using Docker mattermost 
```  
Mattermost Team Edition

All your team communication in one place, instantly searchable and accessible anywhere.
Version: 3.7.0  (3.7.5)
Database: mysql
```

Base settings minus changing the Connects to enable CORS on * and insecure to True.

```js
const headers = {
  Accept: 'application/json',
  'Content-Type': 'application/json',
};
const settings = {
  method: 'post',
  headers,
  body: JSON.stringify({login_id: 'test', password: 'Passw0rd'}),
};
fetch('http://127.0.0.1:8065/api/v3/users/login', settings ).then(function(response) {
  console.log('OK: ' + response.ok.toString());
  console.log('content-type: ' + response.headers.get('content-type'));
  console.log('token: "' + response.headers.get('token') + '"');
  console.log('Token: "' + response.headers.get('Token') + '"');
  console.log('Response Body');
  console.log(response.json());
});
```

Console output from chrome(59.0.3071.29)
```
OK: true
content-type: application/json
token: "null"
Token: "null"
Response Body
```

I then attempted this inside Firefox(45.7.0) and in Firefox i don't get `null` for token.

**Comment by ibigpapa** [comment] 2017-05-03 21:59
More research on this.  I created a simple python flask server using python 3.6, tested chrome with it and found both endpoints didn't return the token.  So now not sure if this is a chrome issue or a behavior that is expected.
```python
from flask import Flask, make_response

app = Flask(__name__)

@app.route('/header', methods=['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'])
def header():
    resp = make_response('', 200)
    resp.headers['Access-Control-Allow-Headers'] = 'content-type, token'
    resp.headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS, PUT, PATCH, DELETE'
    resp.headers['Access-Control-Allow-Origin'] = '*'
    resp.headers['Content-Type'] = 'text/plain; charset=utf-8'
    resp.headers['Token'] = 'yes'
    return resp

@app.route('/noheader', methods=['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'])
def noheaders():
    resp = make_response('', 200)
    resp.headers['Access-Control-Allow-Headers'] = 'content-type'
    resp.headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS, PUT, PATCH, DELETE'
    resp.headers['Access-Control-Allow-Origin'] = '*'
    resp.headers['Content-Type'] = 'text/plain; charset=utf-8'
    resp.headers['Token'] = 'yes'
    return resp

app.run('127.0.0.1', port=3333)
```

No Token in Allowed Header with POST
```js
headers = {
  Accept: 'text/plain; charset=utf-8',
  'Content-Type': 'text/plain; charset=utf-8',
};
settings = {
  method: 'post',
  headers,
};
fetch('http://127.0.0.1:3333/noheader', settings ).then(function(response) {
  console.log('OK: ' + response.ok.toString());
  console.log('content-type: ' + response.headers.get('content-type'));
  console.log('token: "' + response.headers.get('token') + '"');
  console.log('Token: "' + response.headers.get('Token') + '"');
});
```
Output:
```
Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}
OK: true
content-type: text/plain; charset=utf-8
token: "null"
Token: "null"
```

Token in Allowed Header with POST
```js
headers = {
  Accept: 'text/plain; charset=utf-8',
  'Content-Type': 'text/plain; charset=utf-8',
};
settings = {
  method: 'post',
  headers,
};
fetch('http://127.0.0.1:3333/header', settings ).then(function(response) {
  console.log('OK: ' + response.ok.toString());
  console.log('content-type: ' + response.headers.get('content-type'));
  console.log('token: "' + response.headers.get('token') + '"');
  console.log('Token: "' + response.headers.get('Token') + '"');
});
```
Output:
```
Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}
OK: true
content-type: text/plain; charset=utf-8
token: "null"
Token: "null"
```

No Token in Allowed Header with GET
```js
headers = {
  Accept: 'text/plain; charset=utf-8',
  'Content-Type': 'text/plain; charset=utf-8',
};
settings = {
  method: 'get',
  headers,
};
fetch('http://127.0.0.1:3333/noheader', settings ).then(function(response) {
  console.log('OK: ' + response.ok.toString());
  console.log('content-type: ' + response.headers.get('content-type'));
  console.log('token: "' + response.headers.get('token') + '"');
  console.log('Token: "' + response.headers.get('Token') + '"');
});
```
Output
```
Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}
OK: true
content-type: text/plain; charset=utf-8
token: "null"
Token: "null"
```

Token in Allowed Header with GET
```js

headers = {
  Accept: 'text/plain; charset=utf-8',
  'Content-Type': 'text/plain; charset=utf-8',
};
settings = {
  method: 'get',
  headers,
};
fetch('http://127.0.0.1:3333/header', settings ).then(function(response) {
  console.log('OK: ' + response.ok.toString());
  console.log('content-type: ' + response.headers.get('content-type'));
  console.log('token: "' + response.headers.get('token') + '"');
  console.log('Token: "' + response.headers.get('Token') + '"');
});
```
Output:
```
Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}
OK: true
content-type: text/plain; charset=utf-8
token: "null"
Token: "null"
```

**Comment by ibigpapa** [comment] 2017-05-03 22:37
Just incase this is a chromium bug i've submitted a ticket for chrome as well.
https://bugs.chromium.org/p/chromium/issues/detail?id=718208#

**Comment by ibigpapa** [comment] 2017-05-04 16:06
Ok Found the issue.   Mattermost isn't setting the appropriate header field to expose the token header. which is only an issue when dealing with CORS.  https://fetch.spec.whatwg.org/#http-access-control-expose-headers

Updated reproduction code to show.
```python
from flask import Flask, make_response

app = Flask(__name__)

@app.route('/header', methods=['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'])
def header():
    resp = make_response('', 200)
    resp.headers['Access-Control-Allow-Headers'] = 'content-type, token'
    resp.headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS, PUT, PATCH, DELETE'
    resp.headers['Access-Control-Allow-Origin'] = '*'
    resp.headers['Access-Control-Expose-Headers'] = 'Token'
    resp.headers['Content-Type'] = 'text/plain; charset=utf-8'
    resp.headers['Token'] = 'yes'
    return resp

@app.route('/noheader', methods=['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'])
def noheaders():
    resp = make_response('', 200)
    resp.headers['Access-Control-Allow-Headers'] = 'content-type'
    resp.headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS, PUT, PATCH, DELETE'
    resp.headers['Access-Control-Allow-Origin'] = '*'
    resp.headers['Content-Type'] = 'text/plain; charset=utf-8'
    resp.headers['Token'] = 'yes'
    return resp

app.run('127.0.0.1', port=3333)
```

now inside a chrome console on another site's page
```js
const endpoints = ['header', 'noheader'];
endpoints.forEach(function(endpoint) {
  fetch(`http://127.0.0.1:3333/${endpoint}`, { method: 'get' }).then(function(response) {
    console.log(`Will Have ${endpoint}.`);
    console.log(response.headers.get('Token'));
  });
});
```

Output:
```
Will Have header
yes
Will Have noheader
null
```

**Comment by ibigpapa** [comment] 2017-05-04 16:52
Reviewing the code I'd insert the following line on https://github.com/mattermost/platform/blob/master/app/login.go#L108

While this will only account for the login session.  Any other headers you wish to return outside of the safe headers list will need to be exposed at the appropriate location as well.
https://fetch.spec.whatwg.org/#cors-safelisted-request-header 

```go
w.Header().Add('Access-Control-Expose-Headers', model.HEADER_TOKEN)
```

**Comment by lindy65** [comment] 2017-05-04 18:29
Hi @ibigpapa,

Thanks for the time you've taken to investigate and report on the issue!  Appreciated!

Would you like to submit a PR for the code fix you've suggested above?

**Comment by ibigpapa** [comment] 2017-05-04 19:05
Naw,

I didn't test that fixed it.  based on my limited testing in python it should.  I don't have a dev machine at this time setup for a go project to test this and issue a PR.

**Comment by lindy65** [comment] 2017-05-04 19:17
Got it, thanks @ibigpapa,

No worries, I'll ask one of our devs to take a look and post back here with feedback.

**Comment by lindy65** [comment] 2017-05-08 07:03
Hi @federicolucca and @ibigpapa,

I've created a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6514) for our devs to investigate and we can track the issue there.

**Comment by jasonblais** [comment] 2017-05-09 16:51
@federicolucca @ibigpapa 

What is the use case for having Enable CORS set to * and enable insecure outgoing connections also enabled?

**Comment by ibigpapa** [comment] 2017-05-09 17:02
Boots or environments where it's not feasible to use dns for bot\api
integration

**Comment by jasonblais** [comment] 2017-05-17 13:33
Thanks @ibigpapa , we'll investigating the issue in coming weeks. The ticket is currently scheduled for 3.10: https://mattermost.atlassian.net/browse/PLT-6514

**Comment by lindy65** [comment] 2017-05-31 10:39
I'll close this issue off and we can track via the Jira ticket above.

**Closed by lindy65** 2017-05-31 10:39 UTC
