### ISSUE TITLE
User state not set to "away" when suspending

### ISSUE THREAD

**Issue by apriori** [mattermost/platform#6937] opened 2017-07-14 10:39 UTC
#### Summary
When the user suspends his connection mattermost client should react by setting the user as offline immediately. 

#### Steps to reproduce
Use "suspend" under e.g. the windows (native) client and monitor the respective user using a different user on a mattermost service. The user status remains unchanged and gives the false impression of availability.

#### Expected behavior
When clients use "suspend" their status should immediately be changed to "offline".

#### Possible fixes
The local client needs to detect windows going into suspend mode and disconnect from the mattermost service. On resume, a reconnect would be expected.

**Comment by esethna** [comment] 2017-07-18 21:34
Thanks @apriori, a few questions to help narrow down the issue:

1. I'm not sure what you mean by `Use "suspend"`, can you please help explain with a bit more detail? 
1. Just to make sure I understand correctly, you are using the windows desktop app? 
2. If yes, what version of the desktop app are you running?
3. Does the same behavior reproduce using a browser?

**Comment by lindy65** [comment] 2017-08-02 08:43
Hi @apriori,

Just circling back on this issue and your feedback to `esethna's` questions?

**Comment by apriori** [comment] 2017-08-03 06:34
@lindy65 @esethna 
Oh sorry, I completely forgot to respond.

> 1. I'm not sure what you mean by Use "suspend", can you please help explain with a bit more detail?

With suspending I mean the process of putting (in this case) your windows pc into standby mode, therefore the system is not fully shut down, but remains in a standby state. In this case I assume the mattermost native app does not detect this behavior to trigger a client disconnect. One would assume that normal timeouts on the server side trigger, but this is not the case either.

> 2. Just to make sure I understand correctly, you are using the windows desktop app?
> 3. If yes, what version of the desktop app are you running?

That is correct. I use version 3.7.0 of the app.

> 4. Does the same behavior reproduce using a browser?

Yes.

**Comment by lindy65** [comment] 2017-08-14 18:43
Thanks for your feedback @apriori 

Could you tell me what server version is running on the desktop app?  You can find this by clicking on the main menu in Mattermost then selecting "About Mattermost".  Perhaps upgrading to the [latest version](https://about.mattermost.com/download/) of Mattermost will resolve this issue.

**Comment by lindy65** [comment] 2017-08-23 17:19
Hi @apriori,

Is this issue resolved for you?  If so, please let me know so I can close it off.  Thanks!

**Comment by apriori** [comment] 2017-08-25 07:09
Hello @lindy65, no, at least for server version 3.10.0 the issue is not resolved. I recheck after an update.

**Comment by lindy65** [comment] 2017-08-25 07:30
Hi @apriori,

Thanks for your feedback,

You can download [v4.1 here](https://about.mattermost.com/download/).  If you'd like to wait until September, 16th - v4.2 will be released.

**Comment by lindy65** [comment] 2017-08-30 08:10
Hi @apriori,

Circling back on this to see whether your issue is resolved with upgrade to v4.1?

**Comment by lindy65** [comment] 2017-09-06 08:13
Hi @apriori, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Closed by lindy65** 2017-09-06 08:13 UTC
