### ISSUE TITLE
Email should use curly quote instead of straight quote

### ISSUE THREAD

**Issue by leyanlo** [mattermost/platform#4921] opened 2016-12-31 00:12 UTC
Apostrophes should be curly quotes (’) not straight quote (')
<img width="708" alt="screen_shot_2016-12-30_at_7_10_29_pm" src="https://cloud.githubusercontent.com/assets/1285326/21574600/ccfb1084-cec3-11e6-9b83-5e4769ecbf17.png">

**Comment by jasonblais** [comment] 2016-12-31 18:55
I think your email provider (Hotmail, Gmail, Yahoo, ...) controls which apostrophe style is used. Can you compare against other emails you've received to see if they use a curly or straight quote?

**Comment by leyanlo** [comment] 2016-12-31 19:53
The email provider doesn't change which character is used. I can confirm that if you send the correct curly quote character it renders properly in the browser or mail client.

E.g.
<img width="729" alt="screen shot 2016-12-31 at 2 52 45 pm" src="https://cloud.githubusercontent.com/assets/1285326/21579056/d4619d98-cf68-11e6-9bbc-ff4f1da3bb47.png">

**Comment by jasonblais** [comment] 2017-01-05 13:15
I see, thanks @leyanlo. 

We use straight quotes elsewhere in the software -- would your suggestion be to change this in all places?

**Comment by leyanlo** [comment] 2017-01-06 09:18
Yes, all user-facing strings should use curly quotes for apostrophes (‘’) or quotes (“”). Other common typographical mistakes are n-dashes (–) and ellipsis (…) characters. You'll notice that all word-processor apps will auto-correct these characters when typing, but programmers must be vigilant to do these manually for user-facing strings.

Be careful about doing a find-and-replace-all though ;-) https://twitter.com/JohnELewis/status/816389424040833024

**Comment by jasonblais** [comment] 2017-01-20 22:23
Thanks again @leyanlo! I've created a feature request so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html).

https://mattermost.uservoice.com/forums/306457-general/suggestions/17794354-use-correct-typographical-symbols-for-all-user-fac


Appreciate your feedback!

**Comment by it33** [comment] 2017-01-20 22:42
Re-opening for a moment, I was showing @leyanlo the Mattermost app and I thought it was the case where we were inconsistent with use of apostrophes, in which case it would be a bug, not a feature request. 

Leyan, is there an example of inconsistency or was I mistaken? At any rate, I don't see harm in opening a Help Wanted ticket for a contributor to fix this. It's a an easy first contribution that isn't hard to review and test and it does make the product better. 

If we do take this I would propose closing this ticket and opening another, I am just re-opening to discuss

**Comment by jasonblais** [comment] 2017-01-21 18:47
Ah, if we're inconsistent, then I agree it would be a bug report

**Comment by jasonblais** [comment] 2017-01-30 13:04
Hey @leyanlo, wondering if we were currently inconsistent in the usage of straight vs curly quotes, would you know?

Also, wondering if you had a set of correct typographical symbols for dashes, ellipses, etc. as we could include those in the same help wanted ticket.

**Comment by leyanlo** [comment] 2017-01-31 02:35
@jasonblais Within the app itself I didn't see any usage of curly quotes. I did see curly quotes in the handbook if that makes a difference: https://docs.mattermost.com/process/training.html#id11

Curly quotes, dashes, and ellipses are the most common characters and probably all you need to worry about. Full set would be something like this: https://www.w3.org/wiki/Common_HTML_entities_used_for_typography

Interesting to note that Slack automatically replaces quotes, dashes, and ellipses in the message box when you type. Not sure if that's correct or not, but it's there.

**Comment by it33** [comment] 2017-01-31 03:59
Thanks @leyanlo thanks @jasonblais if it's not inconsistent agree it's a feature request for now to change the standard set, and not a bug,     

Closing ticket,

**Closed by it33** 2017-01-31 03:59 UTC
