### ISSUE TITLE
macOS Safari doesnt show preview thumbnails due to promise rejection

### ISSUE THREAD

**Issue by 2075** [mattermost/platform#7183] opened 2017-08-11 14:39 UTC
#### Summary
Browsing a channel with thumbnails does not show thumbnails on Safari but on all other browsers.

#### Steps to reproduce
In macOS Safari, paste or upload an image via drag and drop.

#### Expected behavior
Image should show up in chat stream

#### Observed behavior (that appears unintentional) 
Empty box for the image (compared to other browsers) and image meta info are shown.
Furthermore a promise rejection error shows up in console for every image attempted to render:
`Unhandled promise rejection – TypeError: n.load is not a function. (In 'n.load(a)', 'n.load' is undefined) — file_attachment.jsx:55`

#### Possible fixes
Fix Promise or polyfill(?) for Safari

![image](https://user-images.githubusercontent.com/1140449/29217989-a4d1da0c-7eb3-11e7-8274-9a6ae59904e2.png)

**Comment by hmhealey** [comment] 2017-08-11 15:00
Hi @2075,

What versions of Safari and macOS are you using? I'm not seeing that error myself, but I don't know if I have the same version as you

**Comment by 2075** [comment] 2017-08-11 15:06
The issue was confirmed on various machines, and a promise related error does not really point to a system config related issue (at least not on recent systems), though here it is:

mattermost 4.0.0  (4.0.3)
macos 10.12.6
safari 10.1.2

**Comment by hmhealey** [comment] 2017-08-11 15:37
Okay, I'm on the same version, but I can't reproduce it. I know what code is responsible for this though, and I know why it may be causing the problem. I've filed a Jira ticket if you'd like to track the progress on this: https://mattermost.atlassian.net/browse/PLT-7397

**Comment by hmhealey** [comment] 2017-08-11 19:25
@2075 I've submitted a fix for this. If you get a chance, can you able to see if it still happens on [this test server](http://i-04ab90e039ce1797b.spinmint.com:8065/)? You can log in with the username `test` and the password `passwd`

**Comment by 2075** [comment] 2017-08-11 19:44
@hmhealey excellent, that works like a charm!
what did you change?

**Closed** 2017-08-14 07:10 UTC
