### ISSUE TITLE
Don't send Notifications for @-channel @-here @-all in certain cases

### ISSUE THREAD

**Issue by ssstrat11s** [mattermost/platform#7076] opened 2017-08-01 12:57 UTC
#### Summary
Special tags of @-channel, @-here @-all (without hyphens) are used with code blocks and other features, notifications should not be sent in the UI or email.

#### Steps to reproduce
Discovered on our organization's 3.9.0 build, although I don't believe this has changed since.
Using @-all (etc.) always applies in the content of messages. It's unlikely that it is desired for these tags to apply if they are within certain markdown, including, but probably not limited to:
- \`\`\`code backticks\`\`\` (all on one line - which sometimes people do)
- \> block quotes
- text formatting (italics, bold, strikethrough)
- links (in particular the display portion

It appears (at least in backticks, not positive on the others) that an email is not sent, even to people not currently logged in, but the channel still gets a notification within the UI for all persons.

#### Expected behavior
When special tags of @-channel, @-here @-all (without hyphens) are used within certain features, notifications should not be sent in the UI or email.

#### Observed behavior (that appears unintentional) 
When special tags of @-channel, @-here @-all (without hyphens) are used within certain features, notifications are generally not intended to be sent to users

#### Possible fixes
I believe the issue lies in the GetExplicitMentions function here:
https://github.com/mattermost/platform/blob/8a91235fb3cdc8d094dbc2eaa0d7baa447132b3c/app/notification.go#L729

To account for this issue, I'm assuming that for the triple-backticks being on one line the code block pattern:
https://github.com/mattermost/platform/blob/8a91235fb3cdc8d094dbc2eaa0d7baa447132b3c/app/notification.go#L822
or the inline code pattern:
https://github.com/mattermost/platform/blob/8a91235fb3cdc8d094dbc2eaa0d7baa447132b3c/app/notification.go#L825
could be updated to account for this.

For other markdown that should also be stripped from the mention-check, I assume additional patterns would be added to strip out the appropriate markdown sections prior to scanning for mentions.

**Comment by lindy65** [comment] 2017-08-02 08:03
Hello @ssstrat11s,

Thank you for your detailed feedback,

At mentioning no longer sends notifications if used in code blocks and code backticks. I believe this was fixed in v3.10.  Also new in v3.10 was the warning displayed if you use at-all and at-channel in a channel with many channel members.

![image](https://user-images.githubusercontent.com/13020833/28863089-dd718eaa-7767-11e7-951f-0bf1a878661f.png)

![image](https://user-images.githubusercontent.com/13020833/28863106-f115586a-7767-11e7-8ed2-aa1859aee955.png)

The latest version, v4.0.2, shipped on July 31st and you can download it [here](https://about.mattermost.com/download/).

For the other areas you mention at-all, at-channel and at-here should not trigger notifications and emails, I'll ask one of our product managers to give their feedback.

**Comment by esethna** [comment] 2017-08-21 18:37
Thanks @ssstrat11s. I was able to reproduce the issue on our instance of 4.1 where code blocks and back ticks would trigger mentions. Our ticketing system is down at the moment but I will circle back with a ticket link once we are back up.

For the other forms of markdown I would think it is intended behaviour that they fire mentions. Given that all other forms of formatting work, I would also expect mentions to work. Since code blocks and back ticks strip the formatting, they should not fire mentions. Open to discussion, appreciate the feedback.

**Comment by esethna** [comment] 2017-08-24 18:36
Ticket here: https://mattermost.atlassian.net/browse/PLT-7473. Closing to track in JIRA, thanks!

**Closed by esethna** 2017-08-24 18:36 UTC
