### ISSUE TITLE
Mattemost 3.5.0 Upgrade Issues

### ISSUE THREAD

**Issue by vrenjith** [mattermost/platform#4568] opened 2016-11-17 05:29 UTC
I just upgraded to `3.5.0` version of Mattermost team edition and I do see some issues.
* The upgrade was not as smooth as earlier upgrades. Mattermost didn't come up initially and it caused a bit of tension. Eventually it came up after a stop and stop of `mattermost` service (ubuntu upstart)
* @ Mention is very slow. After typing any name it takes seconds for the pop up to appear and this is causing a bit of confusion for users (we have around 300).

**Comment by DPSLynix** [comment] 2016-11-17 13:16
I agree, I had to reconfigure my server (that is, take the original 3.5 config.json and changes it) because it wouldn't accept the 3.4 one.

Also, when switching to a channel, the scroll is (for a small amount of time) at the right position for the last message, and after a very small amount of time it justs scrolls upside by a tiny amount (seem to only occurs on Desktop 3.4 as I don't have this problem on mobile & web).

And last but not least: emoji autocompletion no longer include "simples" emoji as :D :P and such (even if they are still replaced in the message), which is really boring when typing fast (because "Hi :P" gets replaced by "Hi :pensive : " just before sending your message).

**Comment by jasonblais** [comment] 2016-11-17 13:29
Thanks for the feedback, which database version are you using @vrenjith @DPSLynix ?

Other notes:
 - have forwarded feedback for @ mention autocomplete
 - ticket for scrolling bug: https://mattermost.atlassian.net/browse/PLT-4779
 - ticket for emoji issue here: https://mattermost.atlassian.net/browse/PLT-4780

**Comment by DPSLynix** [comment] 2016-11-17 13:34
@jasonblais I'm using the MySQL driver with a MariaDB host, when starting to boot mattermost on my original 3.4 config.json it was saying  "Failed to ping db err:dial tcp: lookup dockerhost on 127.0.0.1:53: no such host".

Note: I'm not using docker, nor a service (I'm running Mattermost in a screen at the moment).

**Comment by DPSLynix** [comment] 2016-11-17 13:40
Also (figured out this just now) the "copy link" option doesn't work, it just empties the clipboard (dunno if it's a bug from platform or desktop):

![image](https://cloud.githubusercontent.com/assets/3002461/20391466/c44f3e5e-acd3-11e6-9e87-e5e58aaee10a.png)

**Comment by Lulucmy** [comment] 2016-11-17 13:42
Hello,

I'm in the same Mattermost as @DPSLynix and I have an other problem : When I want to go in a new channel,  the description doesn't appear.

**Comment by DPSLynix** [comment] 2016-11-17 13:50
Gif for @Lulucmy bug (which I don't have, Windows desktop):
![image](https://cloud.githubusercontent.com/assets/3002461/20391785/2769717a-acd5-11e6-943f-011777f95b38.png)

**Comment by hmhealey** [comment] 2016-11-17 14:20
@DPSLynix Could you possibly send your original 3.4 config with any sensitive fields removed? There shouldn't have been any breaking changes to the config in 3.5, but I'm wondering if it's something that was added in a previous release that was just using the default before.

Also, was your old config stored in the standard path at `config/config.json`? That "failed to ping db" error sounds like it was loading the default config file and not your edited one.

**Comment by jasonblais** [comment] 2016-11-17 15:45
Thanks @DPSLynix and @Lulucmy! 

I'll file a bug for the screen you posted:

![image](https://cloud.githubusercontent.com/assets/13119842/20396041/e48e64c2-acb2-11e6-9e79-a9d0717bae6f.png)
 

If you find additional issues on the desktop app that cannot be reproduced on the browser, please help report them on the [desktop repo](https://github.com/mattermost/desktop/issues/new).

For product defects that also reproduce on the browser, please [help file a separate bug report using the process outlined here](https://www.mattermost.org/filing-issues/).

**Comment by DPSLynix** [comment] 2016-11-17 15:51
@hmhealey : Sure.

I retrieved it via a diff file I created yesterday to compare the two config files so here is it.

[old_config.zip](https://github.com/mattermost/platform/files/597805/old_config.zip)

Also, yes my old config file was stored there, I can't tell the mistake is not on myself, maybe I screwed up somewhere.

Anyway, keep the hard work, Mattermost is amazing and getting better and better every update!

**Comment by recycled-bin** [comment] 2016-11-17 17:57
![image](https://cloud.githubusercontent.com/assets/23529683/20400540/cd98348c-acfd-11e6-93ec-c51342a56821.png)

I had a seamless upgrade (percona mysql) but there were 3 issues which were immediately visible:
- the annoying scrolling issues already described above
- top header info bar for direct messages do disappear from time to time (see screenshot above) ... haven't noticed any reproducible behaviour so far
- can't really test webrtc ... I've filled in mattermost test webrtc settings but whenever one of both parties accepts the call, it says "There was a problem connecting the video call."

Otherwise, thanks for the great product!

Cheers, guys!

**Comment by hjc1710** [comment] 2016-11-18 21:50
Another issue I'd like to report is that threaded replies to messages from integrations are not properly marked as sent and create an endless retry loop. This is easier to explain with a screenshot.

![screenshot from 2016-11-18 16 43 41](https://cloud.githubusercontent.com/assets/1062500/20447763/a36acda8-adae-11e6-95f8-cab72dad0319.png)

In the screenshot above, in the red box, you'll notice the Retry and Cancel buttons. These appear anytime you reply to an Integration in a thread, which I have confirmed with both our Jenkins and GitHub integrations. If you press Retry, it appears nothing happened and the box does not go away. If you then refresh the page, you will see the original message you sent successfully in the chat, and you will see a message for every single time you pressed Retry. If you see the chain of :grimacing: from `neilzo` in the chat, that is caused by him pressing Retry repeatedly.

I can reproduce this every time regardless of which integration I reply to. Let me know if you want a dedicated ticket for this.

Finally, I would also like to say that I can't really test WebRTC either and am hitting the same issues @recycled-bin is, where I can start the call and right when someone accepts we immediately get an error saying "There was a problem connecting the video call."

Thanks so much for the great product though guys. We've gone through about 5 or 6 major releases without a single issue, which is super impressive.

I look forward to seeing these fixed!

Cheers!

**Comment by eligundry** [comment] 2016-11-18 21:58
I also can't see when people are typing in the channel or in PMs. I dunno if this was ticketed anywhere, but I'd like to see this again.

**Comment by vrenjith** [comment] 2016-11-19 17:59
Another one - The preview does not show the @mentioned names as links.

**Comment by jasonblais** [comment] 2016-11-21 15:01
Thanks everyone!

@recycled-bin For the first two issues (scrolling + channel header sometimes vanishing for direct message channels), we have a hotfix planned for 3.5: https://github.com/mattermost/platform/pull/4584

@recycled-bin and @hjc1710 for the WebRTC connection issues, I've created a [new forum thread to help troubleshoot it](https://forum.mattermost.org/t/troubleshooting-there-was-a-problem-connecting-the-video-call-errors/2521). If you can help answer a few questions about the environment, that would help a lot. Many thanks for trying out the preview feature!

@hjc1710 Can you help create a separate GitHub issue for not being able to reply to messages from integrations? Please help include repro steps so we can try reproducing it on our end (I tried with a few different variations, but didn't notice issues so far).

@eligundry Hm, this should still be showing up, wondering if it's websocket related. If you try updating your theme from **Account Settings > Display > Theme**, does it update automatically without a refresh? How about if you try to edit or delete a post, is a refresh required for the message to be updated or deleted?

@vrenjith Thanks for the report, [filed a ticket for the issue](https://mattermost.atlassian.net/browse/PLT-4790). Please note that the preview mode is a pre-release feature and is expected to have some issues (and hence not turned on by default)

**Comment by eligundry** [comment] 2016-11-21 17:14
@jasonblais my issue isn't with the core platform but rather the desktop client. I will move my issue there.

**Comment by jasonblais** [comment] 2016-11-21 17:35
Ah, got it @eligundry, thank you! We'll take a look at it there.

**Comment by vrenjith** [comment] 2016-11-22 02:47
Will the hotfix cover the @mention delay also?

**Comment by jasonblais** [comment] 2016-11-22 12:52
Not at this point -- but we have a ticket to improve this in 3.6: https://mattermost.atlassian.net/browse/PLT-4626

**Comment by hmhealey** [comment] 2016-11-22 13:31
@vrenjith @jasonblais Actually it was included in 3.5.1 https://github.com/mattermost/platform/pull/4579

**Comment by hjc1710** [comment] 2016-11-29 15:46
@jasonblais - I have opened #4672 to track my specific issue relating to integrations, as you requested. Sorry for the delay! Thanksgiving and a busy work schedule threw a wrench in my plans.

If you need any other details in that ticket, please let me know! Would love to get this solved!

**Comment by jasonblais** [comment] 2016-11-30 04:53
Thanks @hjc1710! Much appreciated, thank you for writing such a clear and complete bug report!

I'll take a closer look tomorrow and try reproduce it.

Thank you once more!

**Comment by jasonblais** [comment] 2016-11-30 04:54
I'll close this thread as there haven't been new 3.5.0 issues and each one reported here have been addressed, or a Jira ticket has been created for them.

Thanks everyone for your reports! If you find new issues, please [help file a bug report for it](https://www.mattermost.org/filing-issues/).

**Closed by jasonblais** 2016-11-30 04:54 UTC
