### ISSUE TITLE
Domain Name Restriction Issue

### ISSUE THREAD

**Issue by Beastie71** [mattermost/platform#2658] opened 2016-04-07 15:13 UTC
Hello,

It appears that though the documentation says you can put in a comma, separated list of domain names, only the first domain is allowed in the list.  We attempted to add in additional domains and were not able to get them to work.  To verify that it was not case sensitive we tried both how the use had tried putting it in as well a straight lower case:

libertymutual.com, Liberty-IT.co.uk, liberty-it.co.uk

The error returned was:

[2016/04/07 11:01:42 EDT] [EROR] /api/v1/users/create:createUser code=500 rid=975rak8e1jna3mi4e87teffu5c uid= ip=10.179.120.148 The email you provided does not belong to an accepted domain. Please contact your administrator or sign up with a different email. [details: ]

I was able to get around this by removing any domain restrictions.

Thanks, any questions please let me know.

Michael

**Comment by esethna** [comment] 2016-04-11 20:42
Thanks for the report @Beastie71, I'll add this to our testing plan for v2.2 and circle back tomorrow.

**Comment by esethna** [comment] 2016-04-15 22:49
@Beastie71, I cannot seem to repro this as you've described. I used a comma to separate two domains in the system console setting "Restrict Creation To Domains". I was able to verify that both domains specified allowed team creation and user creation, but other domains returned an error. Can you provide additional information on your version of Mattermost and the browser/operating system you're using?

**Comment by it33** [comment] 2016-04-17 03:09
Hi @Beastie71, @esethna will be on extended travel so I'm [opening a Jira ticket to track this](https://mattermost.atlassian.net/browse/PLT-2614). My guess is it's because you have multiple periods in the domain and my guess is we might not handle that well. Either way, the Jira ticket will have the result of the investigation, so closing this for now. 

Thanks for the report!

**Closed by it33** 2016-04-17 03:09 UTC

**Comment by it33** [comment] 2016-04-17 05:30
Hi @Beastie71, 

The issue was checked with domains using multiple periods in the domain and could not be reproduced. 

Under Restrict Creation To Domains can you try entering `libertymutual.com, liberty-it.co.uk` and see if it works? 

If not, please help file a new ticket and we'll investigate?

**Comment by Beastie71** [comment] 2016-04-17 14:36
Okay will do as soon as I am back in the office tomorrow!

Michael

**Comment by Beastie71** [comment] 2016-04-20 14:47
Grrr I'll have to leave it closed at this time as I am unable to get a
resource with a functioning email in that section of the company.  If I can
I will grab more debug information and submit a new ticket.

Thank you for your time!

Michael
