### ISSUE TITLE
When focused on window, typing should type into the textbox

### ISSUE THREAD

**Issue by Agrosis** [mattermost/platform#5052] opened 2017-01-12 20:18 UTC
Kind of in between a (tiny) feature request / bug, but it would be nice if, when focused on the chat window (and not on the textbox), typing automatically starts typing into the chat textbox. Not sure how this would fit in with keyboard shortcuts or anything, but its just a matter of convenience because I usually just click into the window and want to start typing instead of clicking the textbox again.

Haven't seen this issue logged anywhere, and I'd be down to implementing it.

NOTE: I use the OS X desktop client, but its probably a multi-platform issue since its written in react.

**Comment by jasonblais** [comment] 2017-01-13 01:59
Hey @Agrosis! We'd love to have a contribution for this, I completely agree with you and it would be great to have.

We actually have [an open Help Wanted issue for it](https://github.com/mattermost/platform/issues/4142) with some specifications, if you're interested? While the issue has details on the implementation, I imagine there to be corner cases we'd have to work through as we develop and test the feature.
 
I'd love to work with you on it if you're up for it! If you have any questions, you can either
 - [post in the Help Wanted issue](https://github.com/mattermost/platform/issues/4142)
 - [join the Contributors community channel and post a question for other contributors and the core team to help](https://pre-release.mattermost.com/core/channels/tickets) or message me directly (`@jason`) on the public instance

**Comment by jasonblais** [comment] 2017-01-16 19:44
Hey @Agrosis, I'll close this issue since it's a duplicate of #4142 

If you're interested to work on it, let us know! Would be happy to work with you

**Closed by jasonblais** 2017-01-16 19:44 UTC
