### ISSUE TITLE
Statics URL

### ISSUE THREAD

**Issue by AdriVillaB** [mattermost/platform#910] opened 2015-10-02 12:40 UTC
if the application is behind a proxy pass, the statics URL points /statics, in case of http://<ip>/mattermost/statics.

Can I configure the application to introduce that parameter in the URI?

**Comment by coreyhulen** [comment] 2015-10-02 16:29
Hi @AdriVillaB.  I'm not sure I follow.  You have re-configured the /static dir and you want it to be /statics (plural) ? 

We run Mattermost instances behind an Nginx proxy and/or an Amazon ELB proxy without issues.  Steps on configuring Nginx can be found at https://github.com/mattermost/platform/blob/master/doc/install/prod-ubuntu.md.

or maybe you are referring to this issue, https://github.com/mattermost/platform/issues/643?

**Comment by AdriVillaB** [comment] 2015-10-02 16:42
Hi @coreyhulen sorry I didn't explain the problem in a good way.

I have a domain server.mydomain.com and I want to access to Mattermost under the URL http://server.mydomain.com/mattermost. 

The problem that I have is that when I request that URL, the statics and the API URLs points to http://server.mydomain.com/static and http://server.mydomain.com/api.

**Comment by coreyhulen** [comment] 2015-10-03 06:59
Hi @AdriVillaB this is a duplicate of https://github.com/mattermost/platform/issues/643.  We are tracking the issue in Jira as  https://mattermost.atlassian.net/browse/PLT-200.  Short story is Mattermost will only run at the root of a FQDN (fully qualified domain name).

**Closed by coreyhulen** 2015-10-03 06:59 UTC
