### ISSUE TITLE
No push notifications and log without user information with Android store app

### ISSUE THREAD

**Issue by demedos** [mattermost/platform#5885] opened 2017-03-27 12:53 UTC
#### Summary
Push notifications are not working at all in Android and not always working on iOS

#### Steps to reproduce
Install mattermost 3.7.0 and store apps, configure as below

**Enable Push Notifications:** Use iOS and Android apps on iTunes and Google Play with TPNS
**Push Notification Server:** http://push-test.mattermost.com
**Push Notification Contents:** Send full message snippet

#### Expected behavior
Push notifications working

#### Observed behavior
All the log messages are missing the used id after _Sending push notification to_. no ID is logged.
`[2017/03/27 00:27:56 PDT] [DEBG] Sending push notification to with msg of 'demedos: this is a test'`

#### Possible fixes
--

**Comment by jasonblais** [comment] 2017-03-28 00:43
What are your mobile push notification preferences set in Account Settings > Notifications so we can try troubleshoot the issues?

When you say you sometimes receive them on iOS, do you get them for @-mentions or for direct message conversations (or for either one)?

**Comment by demedos** [comment] 2017-03-28 07:43
I'm sorry but since the alerts my colleagues gave me with iOS were just few and pretty vague I can assume that those were configuration issues, so I'd prefer to stick to the Android issue, which I know is concrete.

I got my coworker's phone and noticed that the notifications are working when the app is running in the background, but when is completely closed the push messages are not arriving anymore.
Here are the Android configuration.

**Town Square Notification Preferences:**
![183aa35f-4c21-42a5-9477-2b832ee9134f](https://cloud.githubusercontent.com/assets/16702156/24393813/e4db0842-1399-11e7-94cb-729d8fd34a6c.jpg)

**Phone info:**
![54611ae6-3c53-4591-809b-73e3e52196d5](https://cloud.githubusercontent.com/assets/16702156/24393812/e4daf9ce-1399-11e7-9e4b-efe462c602af.jpg)

**Account Notification Preferences:** (I tried the _Online, away and offline_ option but nothing changes)
![d974eee4-5d13-4378-a84c-e695fbaa75ea](https://cloud.githubusercontent.com/assets/16702156/24393814/e4db3100-1399-11e7-9121-96f1d5261cdc.jpg)

**Comment by lindalumitchell** [comment] 2017-03-31 20:49
@jasonblais @demedos I spent some testing on my Android today, and am seeing mixed results. 

Tested by changing the state of the app, with settings the same as described above each time (push notifications for all activity, trigger when away or offline), then observing push notification behavior: 

1. App is open, then lock screen: Received notification immediately, tapping notification brought me to that message
2. App is open, press home button: Received notification immediately, tapping notification brought me to that message
3. Close app by pressing phone's back button (verified Mattermost does *not* appear in Active Apps list): Received notification immediately, tapping notification got stuck on Mattermost loading screen (white screen with large blue Mattermost logo in center). 
Note: From here I had to either force quit from Active Apps screen or press home button and tap Mattermost icon to get into app (tapping icon to open app did bring me directly to the post from the notification)
4. Force close app by tapping END from Active Apps screen (verified Mattermost does not appear in Active Apps list): Did not receive any notifications

I do know that there are occasionally delays from the time a message is posted to the time the push notification is received (a result of phone services, not the app). Could something like that be in play here, but also related to the state of the app when the message is posted? @demedos did you notice if you received any of the expected push notifications after some delay? 

It sounds like differences among Home button, Back button, and force quit have to do with what cached info is stored (or for how long), so maybe something is going on there?

Please let me know if you want me to do any further testing; I'm happy to help.

**Comment by demedos** [comment] 2017-04-03 08:15
@lindalumitchell Thank you very much for your testings.
As you said, the problem occurs when the app is completely closed from the active apps window. 
I did not noticed delay of the notifications, the problem is the state of the app when it's not Active.

**Comment by jasonblais** [comment] 2017-04-03 13:54
Thanks all! Ticket created here https://mattermost.atlassian.net/browse/PLT-6171

**Comment by demedos** [comment] 2017-04-04 07:49
Should I open a new issue for the log lacking the user IDs? Honestly I don't know if it's related to this Android issue

**Comment by jasonblais** [comment] 2017-04-17 13:53
Thanks @demedos, 

the issue should now be fixed on the [second-generation mobile apps released in Beta](https://github.com/mattermost/mattermost-mobile).

**Comment by demedos** [comment] 2017-04-18 07:26
@jasonblais thank you, what about the current release app (the webview)?

**Comment by jasonblais** [comment] 2017-04-18 23:26
Sorry @demedos, I was mistaken. The issue isn't fixed.

In fact, it appears that the library we've used doesn't support it, where force-closing the app causes issues with push notifications.

We're investigating it at the moment both the for the currently released app (in webview) and the second-generation mobile apps.

The progress can be tracked here https://mattermost.atlassian.net/browse/PLT-6171

PS: I included a note in the ticket about the user_id not being logged either.

**Comment by demedos** [comment] 2017-04-19 07:44
Thank you @jasonblais , altough I think the logging issue may be related to something else. Let's see if the [react-native-push-notification](https://github.com/zo0r/react-native-push-notification/issues/388) gets fixed

**Comment by jasonblais** [comment] 2017-04-26 21:04
Cool, thanks @demedos 

I'll close this issue and we can track the progress in https://mattermost.atlassian.net/browse/PLT-6171

**Closed by jasonblais** 2017-04-26 21:04 UTC

**Comment by demedos** [comment] 2017-05-15 09:01
@jasonblais I figured out something else.
The same problem occurred with Slack, and the problem turned out to be related to Huawei and Xiaomi devices and their battery saving modes, which kills all the apps not in their 'whitelist'. Following the procedure written [here](https://android.stackexchange.com/a/169764) solved the problem, this may work for mattermost too

**Comment by jasonblais** [comment] 2017-05-15 21:27
Awesome, thanks @demedos! Really appreciate coming back to us. I've added it to the ticket and let the mobile app team know.

It sounds like it might help resolve the issue to other Mattermost users too, so a huge thanks for this!
