### ISSUE TITLE
[ERROR] duplicate key value violates unique constraint "pg_class_relname_nsp_index"

### ISSUE THREAD

**Issue by smeapng** [mattermost/platform#4562] opened 2016-11-16 12:54 UTC
Hello,

#### Summary
During the mattermost migration from V3.4.0 to V3.5.0, I encountered an error with the migration of the POSTGRESQL database schema.

#### Steps to reproduce
Do the mattermost update from v3.4 to v3.5 and look at the mattermost and postgresql logs.

POSTGRESQL: 9.3
Mattermost: 3.4

#### Observed behavior
In mattermost log : 
```
[2016/11/16 10:42:40 CET] [INFO] Traduction chargées de 'fr' vers '/opt/mattermost/i18n/fr.json'
[2016/11/16 10:42:40 CET] [INFO] Version actuelle 3.5.0 (3.5.0/Tue Nov 15 18:55:53 UTC 2016/3f19ccf1b1a6efdcc990cf8a02
70ec4ffc0c6e22/none)
[2016/11/16 10:42:40 CET] [INFO] Entreprise Activé : false
[2016/11/16 10:42:40 CET] [INFO] Le dossier de travail actuel est /opt/mattermost
[2016/11/16 10:42:40 CET] [INFO] Fichier de configuration chargé depuis /opt/mattermost/config/config.json
[2016/11/16 10:42:40 CET] [INFO] Le serveur démarre...
[2016/11/16 10:42:40 CET] [INFO] Ping de la base de données sql master
[2016/11/16 10:42:49 CET] [CRIT] Impossible de créer l'index pq: duplicate key value violates unique constraint "pg_class_relname_nsp_index"
```

In postgresql log : 
```
2016-11-16 10:42:49 CET ERROR:  duplicate key value violates unique constraint "pg_class_relname_nsp_index"
2016-11-16 10:42:49 CET DETAIL:  Key (relname, relnamespace)=(idx_posts_user_id, 2200) already exists.
```

Have you ever encountered the problem? Is this a primary error knowing that the service is still rendered despite the error.

Thank you.

Cordially.

**Comment by hmhealey** [comment] 2016-11-16 14:51
Hi @smeapng,

That's an interesting problem. Does that error message show up every time you restart Mattermost or was it just the first time you started it up after upgrading? What is printed if you connect to the database and run `select 'idx_posts_user_id'::regclass;`?

**Comment by smeapng** [comment] 2016-11-16 15:14
Hi @hmhealey ,

Thank you for your answer.

The error message appears when I realize the upgrade from 3.4 to 3.5. If I restart mattersmost, I do not have the message.

The result of the command ```select 'idx_posts_user_id'::regclass;``` :
```
mattermost=# select 'idx_posts_user_id'::regclass;
     regclass      
-------------------
 idx_posts_user_id
(1 row)
```

Thank you.

Cordially.

**Comment by hmhealey** [comment] 2016-11-16 15:41
Okay, it looks like the upgrade was successful despite the error message. I'll leave this issue open for a few days in case anyone else has the same issue, but that error seems to be harmless.

**Comment by jasonblais** [comment] 2016-11-28 06:08
Given this was resolved and there have been no other reports so far, closing the issue

**Closed** 2016-11-28 06:07 UTC

**Comment by SephReed** [comment] 2019-12-20 18:02
I just got this issue.

**Comment by jasonblais** [comment] 2019-12-20 20:18
Hi @SephReed, thanks for the note. Would you be open to help create a new GitHub issue with a summary of steps you took and observed/expected behaviour?

**Comment by SephReed** [comment] 2019-12-20 23:02
It's super random.  Only happened once, hasn't been a bother since.  Sorry I couldn't be more help.

I think maybe the issue has something to do with too quickly adding/removing constraints.  In order to assert a constraint, the easiest way is to `DROP CONSTRAINT IF EXISTS` it and re-add it.  

There should likely be a way to `ADD CONSTRAINT IF NOT EXISTS` instead.
