### ISSUE TITLE
Search: Auto-complete when typing “in:" fills in first channel name directly

### ISSUE THREAD

**Issue by princehorn** [mattermost/platform#6628] opened 2017-06-12 12:30 UTC
#### Summary
While typing in the search input field the key word "ui:" to search in a dedicated channel, the auto completion adds the first channel from the channel list directly after the ":". There is no possibility to type in your desired channel name.

#### Steps to reproduce
Version: 3.7.0
Client: Windows 
Focus search input field and type "in:"

#### Expected behavior
The system may present me a list of suggested channel names when I type "in:" **and** the first letters of a channels name. The suggestion might be selected (e.g. cursor keys/ mouse click) or the auto completion may be accepted (e.g. by using TAB key).

#### Observed behavior
Focus in the search input field, the system auto completes the first channel name from the list of channels when typing "in:", directly after the character ":" was typed. The user has no possibility to write a channel name.

**Comment by lindy65** [comment] 2017-06-13 08:07
Hi @princehorn,

Thanks for your feedback,

Could we have your help upgrading to the [latest version](https://about.mattermost.com/download/) of Mattermost?  

Version 3.10 will be released on June 16th so you might wish to wait until then to upgrade.

**Comment by lindy65** [comment] 2017-06-28 09:12
Hi @princehorn, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the latest version. 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Closed by lindy65** 2017-06-28 09:12 UTC
