### ISSUE TITLE
Missing send button on mobile devices prevents sending message

### ISSUE THREAD

**Issue by sascha-frinken** [mattermost/platform#4368] opened 2016-10-28 11:40 UTC
#### Summary

Send button is mising in app and browser and enter key does not send the message on a mobile device.
#### Steps to reproduce
1. Open app or browser with a mobile device that has a width > 768px
2. Type a message
3. Try to send message by hitting the enter key
4. Mesage will not be send as the enter key only creates new lines
5. No option to send the message with the green paper plane send button
#### Expected behavior

Green paper plane send button is visible for mobile devices as enter key is no option to get the message send.
#### Observed behavior

Green paper plane send button is invisible as the responsive design hides it when width > 768px 
#### Possible fixes

Add a setting to always show the send button.

**Comment by jasonblais** [comment] 2016-10-31 19:02
We just tested on Sony Xperia Z3 and it seems to be working fine.

Which device(s) did this reproduce for you? 

Has anyone else in the community noticed this?

**Comment by sascha-frinken** [comment] 2016-10-31 19:22
I am on a Google Pixel C android tablet.
Does "working fine" mean you see the send button or does it mean you can send a message by hitting the enter key?
Once again the main problem is that at least on my android devices a message can not be send without pushing the green send button. The responsive design hides the button whe the screen is wider than 768px, no matter if you are on a mobile device or in the app or a desktop browser.

**Comment by jasonblais** [comment] 2016-10-31 21:17
Sorry for being ambiguous --- by "working fine" I meant that the green paper plane was visible on the Sony Xperia Z3 and therefore sending messages has been successful. 

That being said, I just realized the screen width isn't >768px and hence doesn't satisfy the issue criteria you gave previously.

I've created a [Jira ticket for us to track](https://mattermost.atlassian.net/browse/PLT-4590), would you be interested in helping with a fix?

**Comment by esethna** [comment] 2016-11-07 19:14
Closing, the fix is already submitted for v3.5.

https://mattermost.atlassian.net/browse/PLT-4590

**Closed by esethna** 2016-11-07 19:14 UTC
