### ISSUE TITLE
Keyboard shortcut (ctrl+k) triggers javascript error after one character

### ISSUE THREAD

**Issue by jabis** [mattermost/platform#3460] opened 2016-06-30 16:17 UTC
#### Summary
Some keyboard shortcuts, mainly ctrl+k, throw JS errors after upgrade from 3.0.2 to 3.1.0  

#### Steps to reproduce  
Upgrade from release 3.0.2 to 3.1.0 everything goes smooth. 
Open up MM, set up debug logging and developer tools to true, 
try the new `ctrl+k` shortcut, enter first letter - no prob, enter second letter, receive javascript error as below: 
``` mattermost.log
/api/v3/general/log_client:client code=0 rid=[redacted] uid=[redacted] ip=[redacted] 
msg: Uncaught TypeError: Cannot read property 'username' of undefined row: 21 col: 13187 stack: TypeError: Cannot read property 'username' of undefined url: https://[redacted]/static/bundle-3.1.0.js [details: ]  
```

#### Expected behavior
Change channels from prompt

#### Observed behavior
Javascript error, and after that most of the other keyboard shortcuts also won't work, at least up until next server restart.

#### Additional information
Upgrade process had no errors, build version is downloaded from the releases page 
``` upgrade.log  
[2016/06/30 16:28:04 CEST] [WARN] The database schema version of 3.0.0 appears to be out of date
[2016/06/30 16:28:04 CEST] [WARN] Attempting to upgrade the database schema version to 3.1.0
[2016/06/30 16:28:04 CEST] [WARN] The database schema has been upgraded to version 3.1.0
[2016/06/30 16:36:25 CEST] [INFO] Current version is 3.1.0 (3.1.0/Mon Jun 13 19:08:00 UTC [2016/974238231b9cdbd39a825ec8e9299fbb0b51f6b8/none)
```

**Comment by esethna** [comment] 2016-07-05 02:01
Thanks for the report @jabis! @DavidLu1997 from our team is helping look into this and will report back.

**Comment by esethna** [comment] 2016-07-05 16:27
Hey @jabis, our team is not able to reproduce your issue, but we have a [ticket](https://mattermost.atlassian.net/browse/PLT-3380) to investigate the cause. Closing this issue to track in JIRA, but I'd also like to direct you to the [troubleshooting forum](https://forum.mattermost.org/c/general/trouble-shoot) where members of the community might be able to help you with your specific configuration.

**Closed by esethna** 2016-07-05 16:27 UTC

**Comment by jabis** [comment] 2016-07-05 16:44
I'll contribute a little more info, the same issue happens with a few more users, mainly the users which were initial team admin users. 

Later accounts are mainly gitlab-linked ones, and do not seem to suffer from this behaviour at all. Reading the ticket, it seemed like quite the same behaviour, though we do not have LDAP users at all, and everything is quite default - seems a problem with only certain user objects, so I'll try to compare settings and try to reproduce it with new accounts.

**Comment by jabis** [comment] 2016-07-19 20:29
Ok this definitely comes from platform, not desktop client:
`DEVELOPER MODE: A javascript error has occured. Please use the javascript console to capture and report the error (row: 21 col: 13187).` 

I hunted down the line with sourcemaps, and it comes from experimental settings for a user - there were 3 experimental settings behind the user model, now I can only see 2 and toggling on or of will save any changed options (markdown preview et al.) 

Could someone in the core devel group give hints how to reset the user model?
