### ISSUE TITLE
There appears to be a problem with your internet connection.

### ISSUE THREAD

**Issue by Vaelek** [mattermost/platform#2468] opened 2016-03-18 10:55 UTC
After activating the email settings and the preview mode notice goes away, both the native app and the web interface instantly show "There appears to be a problem with your internet connection." upon loading, and it comes back after a minute when dismissing. In my log, I have an "invalid session token" error.

**Comment by lindy65** [comment] 2016-03-21 08:02
Thanks @Vaelek, ticket to track the issue is here: https://mattermost.atlassian.net/browse/PLT-2399

**Comment by lfbrock** [comment] 2016-03-21 13:38
Closing this issue, will be tracked in Jira.

**Closed by lfbrock** 2016-03-21 13:38 UTC

**Comment by dvenske** [comment] 2016-04-02 21:39
I know this was closed, but I can't comment on the JIRA ticket. What solved this for me @Vaelek was to logout and reset password via email. I think the reason this happens is that setting up email also sets up new salts for security tokens.

**Comment by sonjz** [comment] 2016-04-13 22:07
Logout and login fixed it for me.
