### ISSUE TITLE
Can't fetch external images

### ISSUE THREAD

**Issue by jostyee** [mattermost/platform#5808] opened 2017-03-19 12:46 UTC
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
After merging https://github.com/mattermost/platform/pull/5774 , external images cannot be showed properly any longer.

Chrome console log:
```
Access to Image at 'http://s2.quickmeme.com/img/37/37b72743122262b34ff51535842c5c9a4315360060acf006564e1561b8fba8c5.jpg' from origin 'https://pre-release.mattermost.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://pre-release.mattermost.com' is therefore not allowed access.
```

`Enable cross-origin requests from:*` doesn't work.

#### Steps to reproduce
Build then run codes at HEAD

#### Expected behavior
Fetch & display images correctly if set `Enable cross-origin requests from:*`.

#### Observed behavior
![image](https://cloud.githubusercontent.com/assets/88564/24080985/d1562d9e-0ce4-11e7-8d67-ab3f4516e079.png)
![image](https://cloud.githubusercontent.com/assets/88564/24080989/dc52b44c-0ce4-11e7-999b-a65743f1392c.png)

**Comment by hmhealey** [comment] 2017-03-20 16:46
Hi @jostyee, thanks for the report. I'm going to be reverting that change since we're also having the same problem on our instance as well

**Comment by jasonblais** [comment] 2017-03-27 22:59
Closing since #5774 was reverted and the issue is now resolved,

**Closed by jasonblais** 2017-03-27 22:59 UTC
