### ISSUE TITLE
Webhook creator must be part of group for the POST notifications to work.

### ISSUE THREAD

**Issue by pesusieni999** [mattermost/platform#5186] opened 2017-01-25 12:12 UTC
#### Summary
Channel notifications and message posting with webhook not working if webhook creator is not member of channel.

#### Steps to reproduce
1. Create incoming webhook for some channel.
2. Choose another channel or private group (where the hook creator is NOT member).
3. Using the hook POST to the channel chosen in step 2.

#### Expected behavior
POST message is posted correctly and notifications are given to the channel/group members.

#### Observed behavior
No notification is given.
Message is not shown in the channel until the channel is reopened.

**Comment by lfbrock** [comment] 2017-01-27 21:19
Hi @pesusieni999 thanks for the report!

I think this should be fixed next release ([ticket here](https://mattermost.atlassian.net/browse/PLT-5284)), we're just double checking what the expected should be for private groups since you don't really have permission to the channel anymore after you leave it.

**Comment by lfbrock** [comment] 2017-01-30 14:08
Confirmed this works on master for private groups as well, closing this issue + the fix will be available in the net release (March 16th).

![image pasted at 2017-1-26 19-19](https://cloud.githubusercontent.com/assets/9354841/22425997/9d794978-e6cb-11e6-8356-9db85fa5070c.png)

**Closed by lfbrock** 2017-01-30 14:08 UTC
