### ISSUE TITLE
A channel with that name already exists

### ISSUE THREAD

**Issue by Usernot** [mattermost/platform#129] opened 2015-07-03 13:15 UTC
Steps to reproduce:
1. Create channel "test"
2. Delete channel "test"
3. Try to create channel "test"
4. "A channel with that name already exists"

**Comment by it33** [comment] 2015-07-03 13:51
Thanks @Usernot, 

A fix is queued for this by changing the error message to "A channel with that name was previously created". There's a new set of functionality coming up that will not delete channels, but instead archive them, allowing histories to be restored. As part of this, once the name for a channel is taken, a new one cannot be created. 

The workaround is to rename the original channel. 

@rgarmsen2295 this is ticket MM-1416 internally,

**Comment by coreyhulen** [comment] 2015-07-22 19:55
fixed with https://github.com/mattermost/platform/pull/143

**Closed by coreyhulen** 2015-07-22 19:55 UTC
Labels: bug

**Comment by tomtruitt** [comment] 2016-07-22 17:55
"There's a new set of functionality coming up that will not delete channels, but instead archive them, allowing histories to be restored."

@it33 is this still being planned? channel deletion is a hot issue in the feature request forum

**Comment by jasonblais** [comment] 2016-07-22 22:16
Thanks @tomtruitt for the feedback, we have a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-2900) where you can track progress of this feature.

**Comment by PakG1** [comment] 2016-08-04 03:46
@jasonblais I've upvoted that Jira ticket and am watching it.  Definitely hoping for this to be included in the next release.  :)  Here's my story if it helps.

Tried importing data from Slack into a fairly fresh instance of Mattermost.  If a channel already existed with the same name in Mattermost, the Slack data was not imported into that channel.  Sort of makes sense; importer's in beta, I'm sure there are lots of kinks to work out.

To rectify my issue, tried deleting all channels in Mattermost and tried importing same Slack data again.  This time, all imports failed.  Again, figured this was just an importer-in-beta bug.

That's when I decided just start using Mattermost by recreating the channels and using them with a blank slate.  But couldn't recreate the channels because the names were already taken.  That's when I realized that's why the data import failed for channels that already existed too.

Properly labeling the menu option as "Archive" instead of "Delete" would be a first step.  Are there other issues/tickets already logged for unarchiving channels, as well as more gracefully dealing with channel imports when pre-existing channels have the same name as channels to be imported?  I'll totally upvote those too.  :)

**Comment by thearabbit** [comment] 2018-03-29 00:29
I have the same problem

![image](https://user-images.githubusercontent.com/4495160/38063324-b821c8e6-3322-11e8-9e87-e3fbcb5188f0.png)

But when I tried to search `channel name`, it don't have

![image](https://user-images.githubusercontent.com/4495160/38063341-d6466e44-3322-11e8-9774-61763baf4ced.png)

**Comment by xaionaro** [comment] 2018-04-10 13:13
The issue is closed 3 years ago, but the problem is still there :(

**Comment by thearabbit** [comment] 2018-04-10 13:15
Haha

**Comment by jasonblais** [comment] 2018-04-10 13:44
Thanks for the feedback all!

@xaionaro We're tracking the feature with this epic, which adds channel archives https://mattermost.atlassian.net/browse/MM-354

@thearabbit The UI screen you shared seem different from Mattermost. Is that from Slack by any chance?

**Comment by thearabbit** [comment] 2018-04-11 00:50
Sorry, This is on `Slack`

**Comment by MikeLund** [comment] 2018-04-26 11:18
@thearabbit it's not related to this repo (but is's the first Google result for that Slack error), so if you never got an answer, you need to change the filter to "Archived Channels" to see Archived channels in search:
![screen shot 2018-04-26 at 13 16 04](https://user-images.githubusercontent.com/17044744/39302774-1be0688c-4954-11e8-8b0c-93e4a4e43917.png)
Sorry for the noise!

**Comment by thearabbit** [comment] 2018-04-27 03:00
Sorry

**Comment by santiagomoneta** [comment] 2018-10-29 13:45
I'm still seeing this issue today (Oct 2018)... I was asked to create a channel. Slack says that the name is taken but there is no channel (not even archived) group or username with that name. I'm also a Workspace Owner.

**Comment by jasonblais** [comment] 2018-10-29 14:09
Thanks @santiagomoneta - this particular project is for Mattermost, an open-source messaging and collaboration platform (https://mattermost.com).

For Slack questions, you can visit their help forums :)

**Comment by LoganOneal** [comment] 2019-08-21 01:17
Still no fix four years later?

**Comment by niks3089** [comment] 2019-11-27 09:59
Any further updates on this? Is there a script which can be used as a workaround to delete the channels from DB?

**Comment by jasonblais** [comment] 2019-11-27 13:10
Thanks @niks3089 for the follow-up! 

Our command line tool supports the following two use cases:
1. [deleting a channel](https://docs.mattermost.com/administration/command-line-tools.html#mattermost-channel-delete) -- note that this would also delete all messages within that channel
2. [restore the channel](https://docs.mattermost.com/administration/command-line-tools.html#mattermost-channel-restore), then [rename the channel](https://docs.mattermost.com/administration/command-line-tools.html#mattermost-channel-rename) and [archive it](https://docs.mattermost.com/administration/command-line-tools.html#mattermost-channel-archive).

Some of these, if not all, should also be available through the API.

For this particular feature proposal, would everyone be open to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted](http://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by iithost** [comment] 2020-11-19 10:52
Still the same issue 5 years later

**Comment by frasermarlow** [comment] 2021-01-29 19:34
2021.  The issue still exists.

**Comment by Dewsworld** [comment] 2021-02-08 05:55
The issue still exists!

**Comment by ShunnMatsumura** [comment] 2021-08-30 09:36
The issue still exists.

**Comment by shanben7** [comment] 2021-11-04 17:52
This issue still exists. I cannot name my channel `Cypress` even tho i have renamed the Cypress integration bot.

**Comment by m477r1x** [comment] 2022-01-14 12:54
The issue still exists

**Comment by pandrum** [comment] 2022-01-27 10:41
Issue still exists omegalul

**Comment by Arashpirhadi1369** [comment] 2022-04-13 17:54
The issue still exists :(

**Comment by aawdev** [comment] 2022-07-22 17:02
Yeah, many years later, pretty frustrating. Doesn't look like there is a solution either. Time to find another communication app for small dev groups.

**Comment by aayush123** [comment] 2022-09-01 07:27
Wow, this still exists. Just ran into this problem

**Comment by xaionaro** [comment] 2022-09-01 14:23
> fixed with #143

@coreyhulen : May be worth re-opening the issue? :)

**Comment by bygui86** [comment] 2022-10-26 14:36
please reopen this issue and fix it as it's still around :(

**Comment by widjesh** [comment] 2023-01-09 22:52
Guys I found the issue.

So basically the channel still exists, try to use the search bar to search that channel. Once you find the channel, join it and then delete it manually from settings. This is not an issue, but just an unfriendly behavior. Hope this helps

**Comment by JVMartin** [comment] 2023-03-03 17:57
No, this issue still exists, because the offending channel could be private with nobody in it, and there is no way even for workspace admins to fix the issue. It isn't possible to even find the channel in the list.

**Comment by shamitpatel** [comment] 2023-05-24 13:52
I still see this issue...

**Comment by M-ZubairAhmed** [comment] 2023-05-25 09:32
cc @amyblais

**Comment by amyblais** [comment] 2023-05-25 13:19
As the thread here is long and I'm seeing this report for the first time, would someone be open to creating a new Issue via https://github.com/mattermost/mattermost-server/issues/new with the below details?
1. Your Mattermost server version
2. Detailed reproduction steps
3. Observed behaviour
4. Expected behaviour
