### ISSUE TITLE
Bug: Scroll doesn't track to the end of chat in 1.2.0-RC1

### ISSUE THREAD

**Issue by alerque** [mattermost/platform#1395] opened 2015-11-11 09:32 UTC
Since upgrading to 1.2.0-RC1 I've been seeing issues in both FF and Chrome with the main chat window where the scroll tracking which should keep the frame scrolled to the end of the chat only keeps me at N-1. It follows the chat log but the last message is always scrolled off the pane.

**Comment by it33** [comment] 2015-11-12 02:48
Thanks @alerque, appreciate the feedback. We're seeing this intermittently, it's hard to get a consistent repo, is this happening all the time, or just some times, and do you notice any correlating factors, like having this on channels that have embedded images, file attachments or anything? 

We're trying to track it down.

**Comment by alerque** [comment] 2015-11-12 09:12
My initial impression was that it was happening all the time, but that's not the case. It's intermittent, but for me it's a lot of the time. I'll keep my eye out for any consistent correlations.

**Comment by it33** [comment] 2015-11-13 17:39
Still trying to track this down, one ticket we're also trying to repro: https://mattermost.atlassian.net/browse/PLT-1146?filter=10105

**Comment by alerque** [comment] 2015-11-13 17:43
This is still an "impression", but it seems to go wrong most often after a second messages comes across the wire from the same user as the current tail message, whether self or another user. It definitely happens in rooms with zero images or attachments.

**Comment by fungos** [comment] 2015-11-19 19:46
Broken in 1.1.0 (2920) 4ad9e0673ca8950597a290f10db10475b18b67cc too.

**Comment by it33** [comment] 2015-11-22 17:49
Thanks @fungos, thanks @alerque, appreciate the update. We're still trying to get repro steps: https://mattermost.atlassian.net/browse/PLT-1146.

@esethna, can we ask your help to keep an eye on this issue, and circle back here periodically until we get a solution? 

There are a lot of changes to center channel in v1.3, so we need to clear out v1.2 corner cases as soon as we can so the complexity doesn't get out-of-hand.

**Comment by GuillaumeAmat** [comment] 2016-01-05 09:41
@asaadmahmoodspin I saw that you're kind of the UI man in the last few commits ;)
Do you have any time for this issue?

I would like to do it by myself but it would be a first contribution and I don't have much time now... :(

**Comment by asaadmahmoodspin** [comment] 2016-01-07 08:10
@GuillaumeAmat I'm unable to reproduce this issue, we did a bunch of changes to the center channel and that has hopefully fixed this. I'll still keep an eye out for it.

**Comment by alerque** [comment] 2016-01-07 08:17
At least in the last released version, this isn't fixed. I'm still experiencing the same scroll issue now and then—just yesterday it happened to me on a Mattermost 1.3.0 instance in FF 43.0.1.

@asaadmahmoodspin Are you testing with 1.3.0 or a HEAD build?

**Comment by Gmousse** [comment] 2016-01-08 11:12
@asaadmahmoodspin @alerque @GuillaumeAmat  

Hey guys, maybe this issue is related to the method **updateScrolling()** in **post_view.jsx**. 

Indeed, I tried this, and it's working (I commented original code and I add ````this.scrollToBottom()````:

````javascript
        } else if (this.refs.postlist.scrollHeight !== this.prevScrollHeight) {
            this.scrollToBottom();
            // window.requestAnimationFrame(() => {
                // Only need to jump if we added posts to the top.
                // if (this.jumpToPostNode && (this.jumpToPostNode.offsetTop !== this.prevOffsetTop)) {
                //     this.refs.postlist.scrollTop += (this.refs.postlist.scrollHeight - this.prevScrollHeight);
                // }
            // });
        }
}
````

**Can you confirm that it's working ?** Then, I will send a pull request.

**Comment by Gmousse** [comment] 2016-01-08 14:02
ups, this fix doesn't resolve the issue (thx to @GuillaumeAmat ). It's just scroll to the bottom of the page which is not expected. Indeed, here we need to go to the top of the first new message. 
**my bad**

**Comment by bdupharm** [comment] 2016-01-08 14:28
+1

**Comment by danleepw** [comment] 2016-01-11 02:43
I am having the same issue too. The main chat window sometimes won't be scrolled down to show the new message. Chrome 47/ Ubuntu 14.04.3 / Mattermost 1.3.0 Build Number:4896

**Comment by asaadmahmoodspin** [comment] 2016-01-11 09:01
Okay, can repro now. Will have a look.

**Comment by GuillaumeAmat** [comment] 2016-01-11 10:04
@asaadmahmoodspin Great thanks!

**Comment by tyrants** [comment] 2016-01-11 15:41
@asaadmahmoodspin thx !

**Comment by asaadmahmoodspin** [comment] 2016-01-14 18:32
I think I was able to repro another issue and was mixing it with this one, still having no luck reproducing it with the current release, I remember seeing this a while back, but I'm hoping it's fixed.

I was mixing it with an issue where when you open an unread channel the new messages indicator sometimes is slightly off screen, you also aren't at the bottom of the channel but that's expected as we start from the first unread rather than the last.

**Comment by GuillaumeAmat** [comment] 2016-01-15 08:08
It seems that the 1.4.0 release is out. We are going to test it and if the bug is still there, I will try to fix it...

**Comment by asaadmahmoodspin** [comment] 2016-01-15 08:26
Sounds cool, also repro steps would also be appreciated.

**Comment by GuillaumeAmat** [comment] 2016-01-15 09:56
1. Open Mattermost with Firefox
2. Join a channel
3. Wait for a new message
4. The thread doesn't scroll down to show it

**Comment by asaadmahmoodspin** [comment] 2016-01-15 11:53
I'm on OSX 10.11.2, and can't repro that with the steps mentioned above, which OS are you using? Will try with windows.

**Comment by GuillaumeAmat** [comment] 2016-01-15 14:00
Great :)

**Comment by Kemyke** [comment] 2016-01-18 10:12
What do you think, will this be fixed in v1.5? 
Because we experience this almost every time in direct messages window. You can hear the sound of a new message but you have to scroll down manually to see new messages.

**Comment by asaadmahmoodspin** [comment] 2016-01-18 17:26
@Kemyke @hmhealey is working on fixing it. We'll probably do a dot release to fix this issue. So hopefully before 1.5. I understand how irritating it can be.

**Comment by GuillaumeAmat** [comment] 2016-01-25 11:12
@asaadmahmoodspin We are testing the docker image in its dev version, which include the fix from @hmhealey and it seems to work fine!

Thank you all for your hard work!

**Comment by hmhealey** [comment] 2016-01-25 14:18
@GuillaumeAmat Great to hear! I'll leave this issue open for a few more days in case anything else pops up, but hopefully it's fixed for good.

**Comment by asaadmahmoodspin** [comment] 2016-01-25 15:14
Awesome!

**Comment by Kemyke** [comment] 2016-01-25 16:06
Thank you guys, you are awesome! Do you have a release calendare somewhere just to check when will be the v1.5 out?

**Comment by alerque** [comment] 2016-01-25 16:28
@Kemyke Mattermost releases can be observed on the [releases](https://github.com/mattermost/platform/releases) page and like all Github release pages you can add `.atom` to the URL to get [a feed](https://github.com/mattermost/platform/releases.atom) if you want to monitor new releases as they happen.

**Comment by Kemyke** [comment] 2016-01-25 17:41
Thank you, i know that page. But is there a page where i can see the schedule of future releases? So we can plan when should we start deploying the new v1.5.

**Comment by lfbrock** [comment] 2016-01-25 17:45
If you have an account on Jira, you can also view the [Releases Page](https://mattermost.atlassian.net/projects/PL?selectedItem=com.atlassian.jira.jira-projects-plugin:release-page) which has dates of upcoming releases. (They typically are released on the 16th of each month).

**Closed** 2016-01-28 14:47 UTC
