### ISSUE TITLE
Direct message notification doesn't include the message.

### ISSUE THREAD

**Issue by nraynaud** [mattermost/platform#6474] opened 2017-05-22 13:09 UTC
#### Summary
When receiving a direct message, the notification just says "Otherperson sent you a direct message"

#### Steps to reproduce
Send a direct message to someone who has the smartphone app installed.

#### Expected behavior
I would like to see the actual message.

#### Observed behavior
I saw the message "Otherperson sent you a direct message"

#### Possible fixes
Include the message itself in the notification, like all other messaging apps (facebook messenger, SMS, skype). Otherwise just delete subsequent non-acknowledged notifications, because they are just useless.

![img_3147](https://cloud.githubusercontent.com/assets/46941/26310256/7a7510be-3f00-11e7-8e36-0cc143234fc7.PNG)
![img_3146](https://cloud.githubusercontent.com/assets/46941/26310261/7f164d22-3f00-11e7-8a05-11ff8bfb1ac3.jpg)

**Comment by lindy65** [comment] 2017-05-23 08:56
Hi @nraynaud,

Thank you for your feedback,

Could you tell me which version of Mattermost server you have installed?

Also, to clarify, are you experiencing this on Android? (vs iOS)

The issue you're reporting is fixed in our new beta app.  If you'd like to sign up as a tester, you can do so [here](https://github.com/mattermost/mattermost-mobile/blob/master/README.md#testing).

**Comment by nraynaud** [comment] 2017-05-23 09:23
The server is v3.8.2. 
My experience is entirely iOS, the watch thingie is a "notification slave" (I lack proper vocabulary here) on bluetooth from the iPhone, it's not an android watch (I don't even think it qualifies as a smart watch).

We'll check the beta as soon as possible.

**Comment by lindy65** [comment] 2017-05-23 18:44
Hi @nraynaud,

Thanks for your feedback,

Could you help check what your [Push Notification Contents](https://docs.mattermost.com/administration/config-settings.html#push-notification-contents) settings are?  If you have this set to "generic", it might be the cause of the full contents of the message not displaying in the push notification.

Also, just FYI, Mattermost v3.9.0 shipped on May 16th and you can download it [here](https://about.mattermost.com/download/).

Let me know if this solves your issue!

**Comment by nraynaud** [comment] 2017-05-24 13:51
Thank you, the administrator made the change and it works.

**Comment by lindy65** [comment] 2017-05-25 08:25
Great to hear @nraynaud !

I'll close this issue off then :)

**Closed by lindy65** 2017-05-25 08:25 UTC
