### ISSUE TITLE
member invitation emails contain a local link or public URL depending on whether invitation is made through public or internal accessed URL

### ISSUE THREAD

**Issue by finius** [mattermost/platform#1911] opened 2016-01-18 14:22 UTC
Because the URL shown in the invitation mail to join a team is either a local link (eg. "http://10.0.0.10/teamname") or a public link (eg. "http://www.your-accessed-public-domain-name.com/teamname"), external/public users have problems accessing the server URL when they recieve these emails to non internal network users, even if the teamsite is published to the internet. It would be more appropriate to define a public URL for the team which is always provided as a public link to any invited user (regardless of their internal or external state).

**Comment by lfbrock** [comment] 2016-01-20 17:21
Duplicate of 1912

**Closed** 2016-01-20 17:21 UTC
