### ISSUE TITLE
Back button on Android shuts the app down

### ISSUE THREAD

**Issue by kosimus** [mattermost/platform#4808] opened 2016-12-15 16:23 UTC
#### Summary
Using back button to close the left hand sidebar on Android app, shuts the app down.

#### Steps to reproduce

1. Have version 3.5.0 of the app installed on Android 6.0.1
2. Login to your team.
3. Enter any channel.
4. Open the left hand menu (with channels, groups...).
5. Use the device back button to close the menu.
6. Observe that the app is shut down.

Side note: the same happens for the right hand menu.

#### Expected behavior
The back button should simply hide the menus.

#### Observed behavior
As soon as the back button was tapped, the app was shut down. It was not just sent to background, but really shut down. Re-entering the app clearly launches it again and not just puts is back on the screen.

#### Possible fixes
Sorry, not skilled enough to know.

**Comment by jasonblais** [comment] 2016-12-15 18:32
Thanks @kosimus for the report!

By "shutting down", do you mean that the app goes into the background? 

We currently don't have a lot of control over the "Back" button on the Android app, but we're working on new [React Native mobile apps](https://github.com/mattermost/mattermost-mobile), which will let us fix a few underlying issues. Our goal is to release the new apps in early 2017.

**Comment by kosimus** [comment] 2016-12-18 08:45
No, I mean that it is actually switched off. When an app goes into the background, it is simply hidden from view and re-entering the app simply puts it back on the screen. But in this case, the app is completely switched off and an attempt to put it back on the screen results in the app launching again.

I know about the native apps of course, I just thought that this one might be fixed before they're released. As it's really annoying - Android users use the back button all the time, much like ESC button on desktop. So it normally dismisses menus and closes screens inside of applications. If there is nothing to dismiss or close in the app, it sends the app to background, but it's rare to use the back button to actually kill a process.

**Comment by lfbrock** [comment] 2016-12-19 22:48
Hi @kosimus - can you check and see if the app is actually closing completely, or if it's just reloading? 

I think the current apps reload when they are opened after being set to the background, to get any new messages. 

For the Android back button issue - we're working on some new mobile apps using React Native that should work better with the back button.

**Comment by jasonblais** [comment] 2017-01-04 22:50
We haven't received an update so we will assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the latest version. 

If the issue persists, reopen this issue with the relevant information.

**Closed by jasonblais** 2017-01-04 22:50 UTC
Labels: Awaiting Submitter Action
