### ISSUE TITLE
External POST to API cannot create usable channels

### ISSUE THREAD

**Issue by jkae** [mattermost/platform#3675] opened 2016-07-25 20:47 UTC
#### Summary
Created channels by externally POSTing to the API are inaccessible.

#### Steps to reproduce
- Latest compiled from site
- POST to api/v3/users/login to retrieve authentication token.
- POST (with token in header) to api/v3/teams/etc/channels/create json: {"name":"test1","type":"O","display_name":"test1","team_id":"etc","purpose":""}
- View MatterMost team page
- Create channel directly through MatterMost

#### Expected behavior
MatterMost should create a channel with the name test1, displaying as test1, under Channels in the etc team. A new channel with the same name should not be able to be created via the MatterMost interface.
 
#### Observed behavior
MatterMost responds with code 200 and the following json: 
{"id":"\#","create_at":\#,"update_at":\#,"delete_at":0,"team_id":"etc","type":"O","display_name":"test1","name":"test1","header":"","purpose":"","last_post_at":0,"total_msg_count":0,"extra_update_at":\#,"creator_id":"\#"}

Further attempts to create a channel using the same information result in code 500 and this response in the MatterMost console: 
[EROR] /api/v3/teams/etc/channels/create:SqlChannelStore.Save code=500 rid=\# uid=\# ip=\# A channel with that URL already exists [details: id=\#, pq: duplicate key value violates unique constraint "channels_name_teamid_key"]

Channel is assumed to be created, but does not show in list or under the "More" modal.

Channel can be recreated through the interface using the same name and without a purpose/description.

**Comment by jasonblais** [comment] 2016-08-06 04:05
Really sorry for the significant delay here @jkae , 

I will confirm with our team and get back to you on this after the weekend

**Comment by enahum** [comment] 2016-08-07 17:48
Hi @jkae 

It seems the problem is that you're using the `team name` instead of the `team id` in you channel create API call, try and use the Id instead of the name and it should work as expected

**Comment by jasonblais** [comment] 2016-08-11 18:50
Closing the issue for now @jkae, please feel free to reopen if you have further questions

**Closed by jasonblais** 2016-08-11 18:50 UTC
Labels: Awaiting Submitter Action
