### ISSUE TITLE
[Help Wanted] Post a System Message when channel has is Purpose changed

### ISSUE THREAD

**Issue by it33** [mattermost/platform#4686] opened 2016-11-30 23:42 UTC
When someone changes the Purpose of a channel or private group, post a system message indicating the change with: 

`[USERNAME] updated the purpose of this channel from: [OLD_PURPOSE] to: [NEW_PURPOSE]`

Here is an example from existing functionality changing the header of a channel: 

![image](https://cloud.githubusercontent.com/assets/177788/20775952/7c1b8ef0-b712-11e6-83ac-b824664a7e60.png)

**Comment by jasonblais** [comment] 2016-11-30 23:55
Closing, duplicate of https://github.com/mattermost/platform/issues/4333

WIP PR also submitted that will add this functionality: https://github.com/mattermost/platform/pull/4664

**Closed by jasonblais** 2016-11-30 23:55 UTC
