### ISSUE TITLE
Feature Request: trackable (and repeatable) user/channel/post import

### ISSUE THREAD

**Issue by jdeng** [mattermost/platform#786] opened 2015-09-24 17:18 UTC
The idea is to add an external id to imported user/channel/post (e.g., using SHA1 checksum of <source, id>) so that data (e.g., from Slack) can be continuously synced over without maintaining states. 
This is essentially an extended version of slack import.

**Comment by it33** [comment] 2015-11-23 09:15
Hi @jdeng, appreciate the idea. Sorry for the long delay in replying, 

Would you be open to [filing a feature idea in the feature idea forum](http://www.mattermost.org/feature-requests/) so this change could be upvoted by the community? 

We're doing a sweep of feature requests in GitHub Issues and trying to get them into the feature idea forum where they can be seen by a larger community.

Since this issue isn't a [regression or obvious error](https://github.com/mattermost/platform/blob/master/doc/process/overview.md#github-issues), closing for now.

**Closed by it33** 2015-11-23 09:15 UTC
