### ISSUE TITLE
Accepting Pull Requests - Pragma:	no-cache for resources

### ISSUE THREAD

**Issue by gsmet** [mattermost/platform#1890] opened 2016-01-14 16:33 UTC
Hi,

It looks like Mattermost sends a `Pragma: no-cache` header even for all the static resources (images, CSS, fonts, JS...).

It's not a very good idea and it takes unnecessary long to load the Mattermost page.

What is usually used to optimize loading times is to add a ?t=`timestamp of last modified` (this could also work for avatars) or ?v=`mattermost version` to static resources URL and put a large cache header such as one year.

Could it be done in Mattermost?

**Comment by forelabs** [comment] 2016-01-14 20:17
+1

I think the problem is that the static content is served with the same server handler as everything else.
SHould be configured with different headers for static content.

**Comment by esethna** [comment] 2016-01-24 19:56
Thanks @gsmet and @forelabs, ticket created [here](https://mattermost.atlassian.net/browse/PLT-1804).

**Comment by lfbrock** [comment] 2016-01-25 17:58
Closing this issue, it will be tracked in Jira

**Closed by lfbrock** 2016-01-25 17:58 UTC
Labels: Needs Jira ticket
