### ISSUE TITLE
4.x flicker when loading animated gif images

### ISSUE THREAD

**Issue by XANi** [mattermost/platform#7013] opened 2017-07-24 13:09 UTC
When image load in history there is a weird flickering (was looking a bit better in 3.x)

Here is how it looks:

https://www.youtube.com/watch?v=JXHU5EIjxQI

**Comment by lindy65** [comment] 2017-07-25 09:47
Thanks for your feedback @XANi,

I see you are using compact display mode but I could not reproduce your issue loading images from back in January in compact mode.

Could you share a little about what kind of images you're loading?  For instance, I tried loading .jpg and .png images and they load fine without flickering.

Which browser are you using?  Or are you using the Desktop App?

**Comment by XANi** [comment] 2017-07-25 12:11
> Could you share a little about what kind of images you're loading? For instance, I tried loading .jpg and .png images and they load fine without flickering.

Animated cat gifs (that is our test instance we use before we push new version for production). Basically anything else in history is just a bunch of gifs, that sum up to few hundred megabytes.

Here is test: https://gist.github.com/XANi/78bb46fee6e425dfd3097dd98feb4969 ( [raw](https://gist.githubusercontent.com/XANi/78bb46fee6e425dfd3097dd98feb4969/raw/786e23b47042ea686442f4493a761b2b076538ea/gistfile1.txt) )

Just paste it to new channel. (and clear browser cache if needed). And basically the slower your connection is the longer it will flicker. I've tested on 3.6.0 and it does not happen, it does on 4.

What i *think* is happening is that every time gif is loaded the page size change which causes everything below to move down and then JS moves it back up.

Of course, having a bunch of gis at once makes it overblown but it happens in "normal" channels.

> Which browser are you using? Or are you using the Desktop App?

Tested in Chrome in incognito mode. Also happens in FF

**Comment by lindy65** [comment] 2017-07-26 08:01
Thank you @XANi,

I've reproduced the issue using your test.  You could be correct about why it's happening.  I'll pass the issue on to the team and ask for their feedback.

**Comment by lindy65** [comment] 2017-07-28 06:40
Hi @XANi 

We've created a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7246) to fix the issue.

Thanks again for the report :)

**Comment by lindy65** [comment] 2017-08-02 08:33
We can track this issue via the Jira ticket so I'll close it off for now...

**Closed by lindy65** 2017-08-02 08:33 UTC
