### ISSUE TITLE
Web client doesn't load in Firefox ESR 45.8.x

### ISSUE THREAD

**Issue by tumbl3w33d** [mattermost/platform#6428] opened 2017-05-17 09:49 UTC
#### Summary
Web client fails to load in Firefox ESR (45.8.x) when connecting to self-hosted mattermost server `3.9.0`

#### Steps to reproduce
Open the web client in a Firefox ESR (45.8.x)

#### Expected behavior
Web client loads.

#### Observed behavior
* stare at 3 dots that indicate a loading process
* open firebug and check the console
* find a [stacktrace](https://gist.github.com/tumbl3w33d/5bba39362a7defc6b9885994d6368dd7) that informs you about `jQuery.Deferred exception: window.mm_config is null`

#### Possible fixes
N/A

Notes:
* I reproduced that on a colleague's machine to make sure it's not an issue caused by my workstation.
* Deleting the browser cache didn't help
* Doing the same thing in my chromium works
* Connecting via standalone client works

**Comment by lindy65** [comment] 2017-05-18 09:10
Hi @tumbl3w33d,

As I understand it, Firefox ESR is a desktop app version of Firefox for large corporations?

Could you explain a little more about your set-up as I'm wondering whether some settings within the Firefox ESR set-up are blocking Mattermost from loading.

**Comment by tumbl3w33d** [comment] 2017-05-18 11:44
Hi @lindy65,
yes Firefox ESR is a desktop app. It's the LTS version of the browser and not necessarily limited to corporations (although it's attractive for these, of course). When you're not after having the latest features, you gain more stability which is, for obvious reasons, attractive for a homogeneous network of workstations. For developers it can be interesting when they use Selenium and want to have less issues with web driver compatibility.

[Debian 8 (current stable) comes with Iceweasel](https://packages.debian.org/search?suite=jessie&section=all&arch=any&searchon=names&keywords=iceweasel) (rebranded for trademark reasons) which is a Firefox ESR an with a newer package called [firefox-esr](https://packages.debian.org/search?keywords=firefox-esr&searchon=names&suite=jessie&section=all). The reason for the co-existence is that they are transitioning away from the rebranded thing, but that's not relevant for this issue.

I'm running Debian Stretch (that's the upcoming stable, release is soon to come). I don't have any plugins active.

If you need more information feel free to ask.

**Comment by lindy65** [comment] 2017-05-19 06:58
Hi @tumbl3w33d,

Thanks for your feedback!

I'll ask our devs whether they have any help/suggestions for you and post back here once I hear from them :)

**Comment by paepke** [comment] 2017-05-19 07:13
Can confirm that this happens on debian jessie
as a possible workaround you can install the current Firefox ESR 52 from the [debian mozilla team](https://mozilla.debian.net/) which solves the issue for me. Nevertheless this should be fixed in mattermost.

**Comment by jasonblais** [comment] 2017-05-19 13:22
Thanks @tumbl3w33d and @paepke - were there any issues on an older version of Mattermost (if you upgraded to 3.9)?

**Comment by tumbl3w33d** [comment] 2017-05-19 13:33
@jasonblais no issues back at 3.8 and before. It started exactly with the 3.9 update.

**Comment by paepke** [comment] 2017-05-20 10:40
Same here - migrated to 3.9 and it breaks on the ESR 45

**Comment by jasonblais** [comment] 2017-05-20 17:13
Thanks! I've created a Jira ticket for us to investigate: https://mattermost.atlassian.net/browse/PLT-6650

**Comment by jasonblais** [comment] 2017-05-23 18:38
@paepke @tumbl3w33d Just to confirm: This works fine on Firefox ESR 52?

There have been some updates recently that have broken compatibility with older browser versions, and recommend upgrading to Firefox ESR 52.

**Comment by tumbl3w33d** [comment] 2017-05-23 18:59
@jasonblais yeah it works as usual on Firefox ESR 52. It's unfortunate that Debian's ESR package didn't get an upgrade to 52 yet even on Sid (unstable) which I run on my private machine, however, I guess you can just sit this out until 13th of June, when ESR 45 will hit [EOL](https://en.wikipedia.org/wiki/Firefox_version_history#Firefox_45.9.0_ESR).

**Comment by jasonblais** [comment] 2017-05-25 16:55
Thanks again @tumbl3w33d and @paepke 

Given ESR 45 is reaching its end of life in three weeks, we recommend you to switch to ESR 52.

We'll also update our docs for updating the minimum Firefox version requirement: https://github.com/mattermost/docs/pull/1209

**Closed** 2017-05-29 18:38 UTC

**Comment by tpo** [comment] 2017-06-01 09:08
(Same here - migrated to 3.9 and it breaks on my FF on Debian stable)

To recap:

* Mattermost 3.8 works
* your sysadmin upgrades it to 3.9
  (in my case idirectly via a gitlab upgrade)
* Mattermost is now broken on all stable Debian clients
* the Mattermost project closes the issue with "upgrade your Debian installation"

That's pretty lame IMHO. Why not fix the thing that introduced problem in the first place instead? Mattermost is now apparently broken on all systems running ESR 45. How do you know when/if those platforms will (be able to) upgrade?

**Comment by tumbl3w33d** [comment] 2017-06-01 11:27
At some point you need to limit the platforms/versions you support and I find it legitimate to not waste effort on supporting versions that are officially (EOL) not maintained anymore. In addition, if your company decides its chat solution is Mattermost, why not install the (well tested) standalone client then?

**Comment by tpo** [comment] 2017-06-01 13:14
> In addition, if your company decides its chat solution is Mattermost, why not install the (well tested) standalone client then?

Because: if you want to use github, why not use their standalone client too (that is in fact a complete webbrowser + pixie dust)? And if you want to access nyt.com as well, then why not use their standalone client also? And slashdot. And gitlab. And stackoverflow. And redmine. And ... People's machines have only so much RAM. Maybe they'd like it to run applications that in fact really are different applications (say a compiler) or use their RAM for data (editing an image maybe?), instead of running N instances of the same application. I can see you point, but I think the path you're suggesting is a path of ressource and energy waste, which I'd rather not perpetuate.

**Comment by tpo** [comment] 2017-06-14 22:05
Debian stable has updated Firefox to 52.2.0. I can confirm that Mattermost now works in Debian stable with Firefox. That takes some steam out of my argument.
