### ISSUE TITLE
[Help Wanted] Post a System Message when channel is renamed

### ISSUE THREAD

**Issue by it33** [mattermost/platform#4685] opened 2016-11-30 23:36 UTC
When someone changes the name of a channel or private group, post a system message indicating the change with: 

`[USERNAME] updated the channel name from: [OLD_NAME] to: [NEW_NAME]`

Here is an example from existing functionality changing the header of a channel: 

![image](https://cloud.githubusercontent.com/assets/177788/20775952/7c1b8ef0-b712-11e6-83ac-b824664a7e60.png)

**Comment by jasonblais** [comment] 2016-11-30 23:55
Closing, duplicate of https://github.com/mattermost/platform/issues/4333

WIP PR also submitted that will add this functionality: https://github.com/mattermost/platform/pull/4664

**Comment by jasonblais** [comment] 2016-12-01 22:30
Reopening, this was not in the scope of #4333.

If anyone in the community is interested implementing this, let us know!

**Comment by fraziern** [comment] 2016-12-02 11:39
I'll give this a try (still getting up to speed on Golang so I may have questions 😄  ).

**Comment by yangchen1** [comment] 2016-12-02 18:17
@fraziern awesome! Please let us know if you have any questions, or post in pre-release. :)

**Comment by fraziern** [comment] 2016-12-03 22:15
@yangchen1 @jasonblais I see there is a `display_name` and a `name` (aka handle) attribute for each channel. Should there be a message displayed when either is changed, or just the `display_name`? If both, should there be different messages?

**Comment by jasonblais** [comment] 2016-12-05 23:22
Hey @fraziern, an excellent question.

The help wanted issue was originally intended for `display_name` only, but I would see a lot of use cases where it would be useful to know if the `name` has changed as well (renaming the handle can brake public links, bookmarks and integrations, for instance).

[I've queued this for our UX meeting to discuss](https://pre-release.mattermost.com/core/pl/s7qo6jamkpgbjjo6abbguyf51h).

If we were to create a system message when the `name` is updated as well, would you prefer a second help wanted issue for it, or just add it to this issue?

**Comment by fraziern** [comment] 2016-12-06 19:39
@jasonblais I'm happy to tackle both at once... maybe there will be some code reuse opportunities. 😄

**Comment by jasonblais** [comment] 2016-12-06 21:39
Thanks, sounds good @fraziern! I'll let you know after our UX meeting, it's on Wednesday at 8:30am San Francisco time.

**Comment by jasonblais** [comment] 2016-12-08 16:20
Hey @fraziern:

Propose adding a system message only when the `display_name` is changed. The system message is useful in this use case as we want all channel members to be aware that the channel was renamed.

For changing the `name`, the use case is limited as most people don't need to know what the URL is.

**Comment by jasonblais** [comment] 2016-12-08 16:20
Also, [Mattermost Holiday Hackfest](https://about.mattermost.com/hackfest/) starts today, if you're interested in participating :)

**Comment by cpanato** [comment] 2016-12-09 14:11
can I work on this? @jasonblais 
or @fraziern is working on that?

**Comment by jasonblais** [comment] 2016-12-09 14:31
I think @fraziern started work on this :)

**Comment by fraziern** [comment] 2016-12-09 17:11
Yep should have a PR out this weekend. :)

**Comment by tejasbubane** [comment] 2016-12-21 21:09
I guess this can be closed by #4762

**Closed** 2017-01-02 05:43 UTC
Labels: Difficulty: Introductory, Go, Hackfest
