### ISSUE TITLE
User avatars not displaying in chat

### ISSUE THREAD

**Issue by karlbateman** [mattermost/platform#2346] opened 2016-03-07 14:00 UTC
Hi All,
Some strange issue here, user avatars don't display in chat. I am running `./platform` with an NGINX reverse proxy using SSL on Debian Jessie amd64. Attached is a screenshot which illustrates my problem, any idea's? Thanks in advance :smile:

![mattermost-icon-missing](https://cloud.githubusercontent.com/assets/6918791/13571425/c19fc622-e46c-11e5-8b1c-d78eb7ab18c4.jpg)

**Comment by lfbrock** [comment] 2016-03-07 20:12
Hi @karlbateman, 

Does this happen for all users, or just for Bot users? 

It could be that the webhook is posting a lot of consecutive posts, so the profile picture isn't showing up except for in the first message. (This also happens if you post several messages from your own account, the messages following the version show a more compact view where the profile picture isn't shown). 

If this is the case, we have a ticket [here](https://mattermost.atlassian.net/browse/PLT-1812) to change webhooks to always show the profile picture beside posts.

**Comment by karlbateman** [comment] 2016-03-08 07:47
Hey @lfbrock,
Thanks for the quick response :smile: this does indeed happen only for bot users. I will refer to your link for always displaying avatars for webhooks.

**Comment by karlbateman** [comment] 2016-03-08 07:50
Ok, rather odd but it seems they do in fact show up. But when I do a page refresh they disappear?

**Comment by lfbrock** [comment] 2016-03-08 17:48
Not able to reproduce that on our end, does anyone else from the Community see this issue? 

Or @karlbateman, if you find repro steps that cause the profile pictures to not show up please let us know.

**Comment by karlbateman** [comment] 2016-03-11 11:31
After following your [Production Instructions for Debian](http://docs.mattermost.com/install/prod-debian.html#set-up-nginx-server) on NGINX with SSL I got everything running, the only thing which is not functioning correctly is the avatar for my bot. They disappear when I refresh and sometimes never show up at all?

**Comment by lfbrock** [comment] 2016-03-14 14:45
Thanks, is anyone else seeing this on a Debian install?

I'm not able to reproduce the images disappearing on refresh, I believe the missing profile pictures might be happening on consecutive posts by the same bot which will be fixed by [PLT-1812](https://mattermost.atlassian.net/browse/PLT-1812).

**Comment by lfbrock** [comment] 2016-05-03 18:28
Hi @karlbateman, I think this issue may have been fixed on master and should be fixed in the v3.0 release May 16th. If you still see the issue after the update, please re-open this?

**Closed by lfbrock** 2016-05-03 18:28 UTC
