### ISSUE TITLE
Team name validation happens at wrong step

### ISSUE THREAD

**Issue by danbeaulieu** [mattermost/platform#1232] opened 2015-10-29 15:47 UTC
I just started mattermost using docker locally to kick the tires. Going through the initial signup I had to create a team name, url, username, password etc. 

When I got to the password/final step and hit submit it came back with an error indicating 'Name' needs to be 4 characters. Since my name is Dan I thought this was peculiar. However it really means the team name, which is also peculiar because our team name is really 3 characters. OK. So i'll pick TeamFoo as our team name and it happily accepts it...except that it fails when picking the url because the url has Team in it I guess.

It'll be helpful I think if the team name validation happens during the picking the team name step.

**Comment by it33** [comment] 2015-10-30 01:39
Hi @danbeaulieu, thanks for the report! Agree this needs to be fixed, 

There's a [ticket for this accepting pull requests](https://mattermost.atlassian.net/browse/PLT-835) and we're hoping to have it resolved before the next release. 

We're looking for a community member who'd like to knock this out as a [good first contribution project](https://mattermost.atlassian.net/issues/?filter=10206), and if not, then it'll fall into the core team's priority queue, 

We try to balance providing opportunities for the community to participate with product quality,

**Comment by it33** [comment] 2015-10-30 01:43
hi @danbeaulieu, actually it looks like this issue is a duplicate of one reported just a little while ago, will close this issue and track with the prior one: https://github.com/mattermost/platform/issues/1215

Intention is to fix this in v1.2 release.

**Closed** 2015-10-30 01:43 UTC
