### ISSUE TITLE
Accepting Pull Requests: Change Favicon to red when notification occurs and tab is inactive

### ISSUE THREAD

**Issue by jbick** [mattermost/platform#975] opened 2015-10-08 08:17 UTC
The favicon does not change its color to red when a new message arrives in the channel which is currently opened. When Mattermost is currently used (active tab) this behaviour makes sense. However, if Mattermost is opened in another tab (we are using pinned tabs) you are missing messages.
This might be related to #635

**Comment by stephenfin** [comment] 2015-10-08 13:03
I agree - I posted [an idea to implement this](https://mattermost.uservoice.com/forums/306457-general/suggestions/10092801-change-favicon-for-new-notifications). I'd be happy to submit a PR for this in the next few days if not too high priority.

**Comment by it33** [comment] 2015-10-08 14:48
Thanks @jbick, thanks @stephenfin! Would love a PR to improve this!

**Comment by jbick** [comment] 2015-10-09 10:47
I think it would be convenient to alter the page title in the same step, e.g. "(3) Town Square - Teamchat".
This would add a blue dot / glow to pinned tabs in Firefox and other browsers. See [this blog post](http://stephentvedt.com/2012/09/17/firefox-pinned-tab-notifications/) for an example.
@stephenfin & @it33 Do you think this could be part of this PR, too? Otherwise I would create a new issue.

**Comment by stephenfin** [comment] 2015-10-09 14:50
Couldn't agree more. Messenger doesn't do this but WhatsApp and others do. Definite usability improvement.

**Comment by it33** [comment] 2015-10-13 00:36
Thanks @jbick, @stephenfin, I took at look at the blog post and couldn't get the demo to work, neither on Firefox or Chrome, wondering if I'm doing something wrong? 

Proposing a larger ticket to address a number of issues with the tab alert (favicon and page title): https://mattermost.atlassian.net/browse/PLT-642

This is a big change (trying to address a number of issues at once), feedback welcome, as well as PRs to fix parts of this.

**Comment by teetrinkers** [comment] 2015-11-10 12:13
This is also noticable with [Matterfront](https://github.com/lloeki/matterfront), which does not show an unread badge in the task bar when I receive a direct message, have the DM channel open but Matterfront unfocused. I suppose the check introduced in #635 should also check if the tab has the focus.

I might look into this. Does anyone know if `document.hasFocus()` is still the way to go or can I use `document.hidden` from the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API)? Apparently, browser support is pretty good now: http://caniuse.com/#feat=pagevisibility.

**Comment by jbick** [comment] 2015-11-10 14:55
@it33 Sorry, didn't notice your reply. To get the demo to work you need to:
- open the [demo page](http://stephentvedt.com/examples/title-notification/)
- pin the tab
- switch to another tab + wait some seconds

The larger ticket sounds good.

**Comment by it33** [comment] 2015-11-23 08:40
@florianorben, thanks for the [PR](https://github.com/mattermost/platform/pull/1173) for addressing [PLT-642](https://mattermost.atlassian.net/browse/PLT-642)

@teetrinkers, @jbick, @stephenfin, if you're interested in hanging out with the Matterfront team, there is [a Mattermost channel for them](https://pre-release.mattermost.com/core/channels/matterfront).

@jbick, maybe have your help closing this issue if you feel it's been addressed?

**Comment by jbick** [comment] 2015-11-30 13:59
@it33 I'm using 1.2.1 and the issue persists.

To reproduce: (just to be sure we are talking about the same thing)
- Open Mattermost in Browser Tab 1
- Navigate to direct chat with another user X
- Open new Browser Tab 2
- Direct messages *from user X* will not change Favicon or trigger browser highlighting

**Comment by it33** [comment] 2015-12-08 05:23
Adding @esethna to look into this as part of testing v1.3

**Comment by esethna** [comment] 2015-12-08 20:48
@jbick thanks for the follow-up. I can confirm that this is fixed on master and will be included in V1.3

**Comment by teetrinkers** [comment] 2015-12-10 08:49
This still does not work for me:
![notification-private-chat](https://cloud.githubusercontent.com/assets/51070/11710926/23dfff6c-9f23-11e5-8cce-33f023952448.gif)

I expected to get an unread count in the tab header or a red favicon. Or is this another issue?

**Comment by esethna** [comment] 2015-12-11 00:12
Hey @teetrinkers,

Looks like you are on V1.2.1? The fix is on master right now, so it will be available with V1.3 that should be shipping around Dec 16.

**Comment by teetrinkers** [comment] 2015-12-11 13:22
We're using the mattermost-dev docker container from hub.docker.com, currently on build 4760. I thought these were build from master? Well, I'll wait for 1.3 and see how it goes.

**Comment by esethna** [comment] 2015-12-11 17:47
Hi @teetrinkers 

My apologies, looks like this is still an issue on master. The specific case of keeping the channel open when switching tabs was missed in our testing plan. I've filed a bug ticket [here](https://mattermost.atlassian.net/browse/PLT-1506) with the expected being that the favicon turns red and shows the number of unread mentions. Thanks for helping narrow it down.

**Comment by jbick** [comment] 2016-01-13 11:43
@esethna Will this be included in 1.5 for sure?

By "the favicon turns red and shows the number of unread mentions" do you mean something [like this](https://stackoverflow.com/questions/6296574/dynamic-favicon-with-count-like-gmail)?

**Comment by lfbrock** [comment] 2016-01-27 17:31
Closing this issue, it will be tracked in [Jira](https://mattermost.atlassian.net/browse/PLT-1506).

**Closed by lfbrock** 2016-01-27 17:31 UTC
