### ISSUE TITLE
Enabling SendEmailNotification causes panic

### ISSUE THREAD

**Issue by InterHmai** [mattermost/platform#3364] opened 2016-06-16 20:49 UTC
#### Summary
Enabling SendEmailNotification causes a panic and runtime error.

#### Steps to reproduce
3.1.0 (was upgrading from 3.0.3)
SendEmailNotification is enabled

#### Expected behavior
Shouldn't cause a panic.

#### Observed behavior
Error with ./platform

> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
> 	panic: interface conversion: interface is runtime.errorString, not string
> [signal 0xb code=0x1 addr=0x0 pc=0x78090f]
> 
> goroutine 1 [running]:
> panic(0xcd1aa0, 0xc820051b80)
> 	/usr/local/go/src/runtime/panic.go:481 +0x3e6
> main.doLoadConfig.func1(0xc820151d48)
> 	/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/mattermost.go:73 +0x6f
> panic(0xccbec0, 0xc82000a0e0)
> 	/usr/local/go/src/runtime/panic.go:443 +0x4e9
> github.com/mattermost/platform/utils.TestConnection(0xc820011080)
> 	/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/utils/mail.go:82 +0x9f
> github.com/mattermost/platform/utils.LoadConfig(0xc820137b00, 0x22)
> 	/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/utils/config.go:181 +0x10aa
> main.doLoadConfig(0xdce990, 0xb, 0x0, 0x0)
> 	/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/mattermost.go:76 +0x6a
> main.main()
> 	/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/mattermost.go:84 +0x43

**Comment by esethna** [comment] 2016-06-18 00:33
Thanks for the report @InterHmai, can anyone from the community help reproduce this issue?

**Comment by InterHmai** [comment] 2016-06-21 14:54
Someone else on MM community forum with similar issue:
http://forum.mattermost.org/t/enabling-email-notifications-caues-mattermost-not-to-start/1717

More info from my end:
Running Ubuntu 14.04.4 LTS with GitLab Auth.
SendEmailNotification is enabled just to remove preview notification. I don't otherwise have any SMTP settings configured.

Originally on 3.0.3, everything was working fine.
Attempted upgrade to 3.1, no changes to config settings, then Mattermost wouldn't start due to panic error. 

Tried a fresh install to test, no errors.

Then tried line-by-line comparison and test of the config file to default one, and narrowed to SendEmailNotification causing the panic.

**Comment by jasonblais** [comment] 2016-06-22 13:35
Thanks for the report @InterHmai! There was a bug where an invalid json field in the config file or a failed connection with `EmailSettings` may cause this error. It's fixed on `master` and will be in for the next release.

In the meantime, you may try the following steps as a workaround:

1. Stop the server
2. Remove `EmailSettings` from your config.json
3. Start the server
4. From the System Console re-add the Email Settings

**Comment by whiskeyneon** [comment] 2016-06-22 18:02
Actually, the fix for me was simply changing `"SendEmailNotifications": true,` to `"SendEmailNotifications": false,` which saves you form re-entering all of the settings.

**Comment by InterHmai** [comment] 2016-06-23 14:56
Will it still be possible to disable preview mode and also not have a valid smtp server?

In our use case, GitLab is used for auth, and we don't need any of the email features relating to Mattermost (for now anyway).

**Comment by whiskeyneon** [comment] 2016-06-23 19:34
To just remove the nag screen, you can edit `platform/error_bar.jsx` on lines 30 and 31 from
`if (!ErrorStore.getIgnoreNotification() && global.window.mm_config.SendEmailNotifications === 'false') {
            ErrorStore.storeLastError({notification: true, message: Utils.localizeMessage('error_bar.preview_mode', 'Preview Mode: Email notifications have not been configured')});`
to
`if (!ErrorStore.getIgnoreNotification() && global.window.mm_config.SendEmailNotifications === 'false') {
            ErrorStore.storeLastError({notification: false, message: Utils.localizeMessage('error_bar.preview_mode', 'Preview Mode: Email notifications have not been configured')});`

Mind you, when you update you will need to make this change again.

**Comment by lfbrock** [comment] 2016-06-27 19:42
Going to close this issue since it seems solved - @InterHmai, please also feel free to [open a feature request](http://www.mattermost.org/feature-ideas/) on removing the nag screen when preview mode is on. It would be interesting to see if other people are also using similar configurations and would like to have email turned off without the preview mode notice showing up.

**Closed by lfbrock** 2016-06-27 19:42 UTC
