### ISSUE TITLE
Mattermost v1.0.0-rc1 regressions

### ISSUE THREAD

**Issue by lfbrock** [mattermost/platform#835] opened 2015-09-28 16:47 UTC
This is a meta issue for discussing: 
- Potential regressions in [the latest Mattermost release candidate](https://github.com/mattermost/platform/releases/tag/v1.0.0-rc1), and 
- Potential patches to be applied prior to final release. 

Please link to issues you believe may warrant a patch (please do not post issue here). It is the responsibility of the release manager assigned to this issue to decide whether or not to merge a patch for the final release, and to list approved patches below. 

## Approved patches for Mattermost v1.0.0-rc1

- None so far

**Comment by it33** [comment] 2015-09-28 18:30
Dupe of https://github.com/mattermost/platform/issues/834

**Closed by it33** 2015-09-28 18:30 UTC
