### ISSUE TITLE
Auto scroll Outgoing webhook not working (sometimes)

### ISSUE THREAD

**Issue by TheFamousPG** [mattermost/platform#3625] opened 2016-07-19 12:04 UTC
#### Summary
Auto scroll not working when Outgoing Webhook respond. (sometimes)
Here is the bug
https://i.gyazo.com/6def69fd1121aa264b123874ac1b1782.gif

#### Steps to reproduce
Create a outgoing webhook and call https://mathieu.lescaudron.com/test in one of your channels without words. And in the channel say : test or hello or bonjour.

#### Expected behavior
I'm using Windows 10 and Chrome 51.0.2704 and mattermost 3.2.0
Work fine on Firefox.

**Comment by lfbrock** [comment] 2016-07-19 19:47
Thanks @TheFamousPG, created a ticket here for someone to go investigate: https://mattermost.atlassian.net/browse/PLT-3703

**Comment by esethna** [comment] 2016-07-26 17:28
Closing to track in JIRA

**Closed by esethna** 2016-07-26 17:28 UTC

**Comment by jasonblais** [comment] 2016-08-16 05:21
Hey @TheFamousPG, we've been unable to reproduce this consistently on `master` in the past few days.

Wondering if this issue might have been fixed with v3.3?

**Comment by jasonblais** [comment] 2016-08-19 03:57
Glad to hear, thanks @TheFamousPG for confirming!
