### ISSUE TITLE
Team Member & Team Admin Unable To Direct Message

### ISSUE THREAD

**Issue by SERVICEFREAKS** [mattermost/platform#4993] opened 2017-01-06 00:17 UTC
#### Summary
Direct Messages Not Working for Team Members Nor Team Admin's. 

#### Steps to reproduce
MatterMost 3.5.1 Fresh Install On Ubuntu 16

Create any user that is a Team Member or Team Admin. They are unable to then direct message anyone without first receiving a direct message themselves. They must NOT be a System Admin

System Admin's are able to Direct Message anyone

#### Expected behavior
The Message Button appears for Direct Messaging of Users. However when clicked it does not perform the action of opening the direct message window.

#### Observed behavior
![image pasted at 2017-1-5 14-58](https://cloud.githubusercontent.com/assets/11657687/21702759/78f68074-d37b-11e6-9761-5a61ec277238.png)

main.bce07c6….js:25 method=joinChannelByName msg=El canal no existe detail= rid=zytt831tyjfwjbc3c8ne9efkjy

{
  "id": "api.context.permissions.app_error",
  "message": "No tienes los permisos apropiados",
  "detailed_error": "",
  "request_id": "8q4r46egpbr5mmopz3pjz4aqxy",
  "status_code": 403
}

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by jasonblais** [comment] 2017-01-09 05:42
Thanks @SERVICEFREAKS for the report,

1) Are any of these users imported from Slack? There is an [existing issue where Slack imported users cannot initiate direct message conversations](https://mattermost.atlassian.net/browse/PLT-4955), and which is fixed with Mattermost 3.6, to be released on January 16th

2) Can you tell me the operating system and the browser (or desktop app version) they use?

3) What is the setting in **System Console > General > Users and Teams > Enable users to open Direct Message channels with** value set to? In `config.json`, this is the `RestrictDirectMessage` setting in `TeamSettings`

**Comment by jasonblais** [comment] 2017-01-16 19:45
Thanks @SERVICEFREAKS,

We haven't received an update so we will assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the latest version. 

If the issue persists, reopen this issue with the relevant information.

**Closed by jasonblais** 2017-01-16 19:45 UTC
Labels: Awaiting Submitter Action
