### ISSUE TITLE
Custom Emojis Fail to Display

### ISSUE THREAD

**Issue by MaddawgX9** [mattermost/platform#4467] opened 2016-11-04 22:01 UTC
#### Summary
Custom Emojis fail to display in chat until after visiting custom emoji list

#### Steps to reproduce
On the desktop application for Windows 10, start mattermost and navigate into a team.
in one of the chats, without going into the custom emoji list, post a custom emoji.

#### Expected behavior
The emoji should display in the chat window.

#### Observed behavior
Only the literal text ":mycustomemojiname:" appears in the chat window.

#### Possible fixes
N/A

**Comment by jasonblais** [comment] 2016-11-04 23:04
Thanks @MaddawgX9 

What versions of the Mattermost server are you using? [This issue should've been fixed with the 3.4 release](https://mattermost.atlassian.net/browse/PLT-3805).

**Comment by jasonblais** [comment] 2016-11-14 14:31
We haven't received an update so we will assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the latest version. 

If the issue persists, reopen this issue with the relevant information.

**Closed by jasonblais** 2016-11-14 14:31 UTC
Labels: Awaiting Submitter Action
