### ISSUE TITLE
After logging in to an Mattermost team site, Safari on iPad Air (iOS 9.2.1) shows a white/blank page

### ISSUE THREAD

**Issue by finius** [mattermost/platform#2056] opened 2016-02-03 07:30 UTC
Even if login site shows normal, after sending credentisls you get a blank website without any content wheather its an on premise hosting or the pre-release.mattermost.com/core team server.

**Comment by it33** [comment] 2016-02-04 05:23
Tried same setup on iPad Pro iOS 9.2.1 on Safari with pre-release.mattermost.com/core and can't repro. 

Are you on a standard Wifi connection? 
Are you still seeing the issue?

**Comment by finius** [comment] 2016-02-04 06:56
Hi Ian, yes, it still persists! After submitting the login page the browser window is blank.
Just tried it again with http://pre-release.mattermost.com/core - both, Patrick and me were also able to reproduce it on our iPhone 6 with recent iOS.

[image](https://cloud.githubusercontent.com/assets/5287181/12808018/226d322c-cb14-11e5-91ce-b9922ab347ab.png)

**Comment by finius** [comment] 2016-02-04 06:58
And, yes, i am on my reluable home wifi. Everything else is working fine

**Comment by it33** [comment] 2016-02-04 17:30
Thanks Martin, 

Not having success repro'ing, wondering if it's a local region issue. Does anyone else in the community see this?

**Comment by ernetx** [comment] 2016-02-05 11:37
Hi finius,
I have similar problem with one specific user on iPhone 6 (after login window is blank), to fix this I Log-in user with Windows Chrome browser -> Account Settings -> Security -> View and Logout of Active Sessions -> And Logout from all Active Sessions. After that I was able to log-in with iPhone 6 successfully.

**Comment by PSchwarck** [comment] 2016-02-16 22:50
On my Iphone 6 (iOS 9.2.1) i stucked with a white screen on Safari, too. Same issue on WiFi & LTE.
I did lock out of all chrome sessions. I wiped all browser data. No change at all. After Logging in, white screen.
With Chrome 48.0.25.64.104 & FireFox (v1.4 (1405))  i was successful to connect to pre-release.mattermost.com , everything worked fine.
All the best Patrick

**Comment by it33** [comment] 2016-02-21 05:08
Thanks @ernestlel, so we can rule out regions, may I ask which country you're in? 

@PSchwarck, @finius, may I ask your help to see if you can reach Core using the [Mattermost iOS app 2.0](https://itunes.apple.com/us/app/mattermost/id984966508?mt=8)? 

That should be running Safari underneath...

**Comment by PSchwarck** [comment] 2016-02-21 11:54
@it33, @finius   
Hi Ian, i could connect to our 2.0 server and your core-install without any hassle. No white screen so far.
Patrick

**Comment by ernestlel** [comment] 2016-02-28 16:12
Hi @it33, I am in England.

**Comment by lfbrock** [comment] 2016-03-02 15:44
Has anyone been able to reproduce this on Mattermost v2.0?

**Comment by finius** [comment] 2016-03-02 15:45
yes, it's still on my iPad and iPhone when using 2.0 ENT-7

**Comment by finius** [comment] 2016-03-03 08:37
@it33 if needed i could provide you guys a temporary VPN Connection into a german network

**Comment by PSchwarck** [comment] 2016-03-10 20:51
I just tested to connect against 2.1.0rc1 on iOS safari without success. Still everything white. 
On chrome/ Firefox everything works well.

**Comment by PSchwarck** [comment] 2016-03-12 19:55
Well I just got hands on my mother-in-law's iPhone 4s on 9.2.1 and I could access our 2.0 installation. 
So far,
Not working :  iPhone 6, iPad Air 2, iPad 2
Working: iPhone 4s, iPad 2
All devices are on 9.2.1.
Pretty strange to me... ;-(

**Comment by chihoko** [comment] 2016-03-23 13:38
We're testing mattermost and have experienced the same issue on dozens of iphone 6s running ios 9.3 using either safari or ios app. Running latest docker image (v2.1.0). Immediately after entering the team url and clicking the next button see a blank screen with no controls. In the servers logs (anonymised) we see:

```
[2016/03/23 13:33:21 UTC] [EROR] /api/v1/admin/log_client:client code=0 rid=3ae9zncwmt8up86hq4a1fu7r1r uid= ip=1.2.3.4 msg: Invariant Violation: [React Intl] The `Intl` APIs must be available in the runtime, and do not appear to be built-in. An `Intl` polyfill should be loaded.
See: http://formatjs.io/guides/runtime-environments/ row: 10 col: 17772 stack: undefined url: http://123.123.123.123:8065/static/bundle-6562.js [details: ]
```

**Comment by lfbrock** [comment] 2016-03-23 16:33
@chihoko, did you install using docker latest or docker dev? There were some larger changes that went in and master is a little unstable right now, I think the issue you're hitting will be fixed in the next release.

**Comment by chihoko** [comment] 2016-03-23 16:35
@lfbrock docker latest - The next release being 16th April?

**Comment by lfbrock** [comment] 2016-03-23 16:36
Yes, it will be fixed on master before then but April 16 will be the next stable release.

**Comment by tomxtobin** [comment] 2016-03-24 17:28
I just ran into this issue on a QtWebKit browser ([qutebrowser](https://github.com/The-Compiler/qutebrowser)) on Linux, trying to access a local Mattermost instance; I tried both the `mattermost/platform:latest` and `mattermost/platform:dev` images from Docker Hub. I get the same `Intl` error in my console.

I'm not sure I'm entirely following the above conversation; is the fix already supposed to be present in the `dev` image, or is that forthcoming?

**Comment by lfbrock** [comment] 2016-03-24 18:13
Hi @tomxtobin, we don't support that browser but the intl fix for Safari should be on mattermost/platform:dev now. Maybe try updating again and see if that fixes your issue.

**Comment by tomxtobin** [comment] 2016-03-24 18:32
It looks like a `safariFix` string (the function name) should be present in the bundled JS (based on what I'm guessing is the fix in the repo), but it isn't present in the bundled JS on the `dev` image at the moment. Docker Hub says `dev` was last updated five hours ago, but the relevant file was just updated two hours ago. (I don't know how long Docker Hub takes to build new images after a push, though.)

**Comment by zeroware** [comment] 2016-03-29 12:05
Hello,

I have the same problem.
I tried using `mattermost/platform:dev` image and even building the image myself.

**Comment by NickeZ** [comment] 2016-03-31 11:35
We also have this problem..

```
Mattermost Team Edition T0
Version:
2.1.0
Build Number:
6562
Build Date:
Thu Mar 17 16:17:34 UTC 2016
Build Hash:
2cd006474ec8a808b2ea2b0502a842f44cb0b127
```

**Comment by lfbrock** [comment] 2016-03-31 14:10
Hi @zeroware and @NickeZ, 

There was a temporary issue on master (introduced after v2.1) that caused this not to work, it looks like you're on a daily build instead of the official v2.1 release (build date should be Mar 14).  This issue should be fixed on master now.

**Closed** 2016-05-30 13:20 UTC
