### ISSUE TITLE
Last person to leave private channel leaves it in an un-joinable state.

### ISSUE THREAD

**Issue by norganna** [mattermost/platform#2726] opened 2016-04-16 23:09 UTC
If theres a private channel with one person in it, and they leave, the channel, it's forever un-joinable, and there's nobody to invite someone into it.

When the last person leaves, an error appears at the top of the screen:
<img width="323" alt="screen shot 2016-04-17 at 9 07 19 am" src="https://cloud.githubusercontent.com/assets/694366/14584144/e331149c-047b-11e6-8c8b-66b767342798.png">
"We couldn't get the channel member"

If someone goes to create the channel they get a message that the channel already exists.

Possibly needs the ability for admins to be able to assign users into empty channels / join any channel from the console / set channel permissions for users.

Either that or force the last person to leave to delete the private channel possibly...

**Comment by it33** [comment] 2016-04-17 00:19
Thanks @norganna, appreciate your finding this. Agree this seems like a bug. 

Will defer to @lfbrock, who is travelling, so might process later in the week.

**Comment by GuillaumeAmat** [comment] 2016-04-20 09:51
@it33 Dunno if that's related to my issue but I see a lot of « We couldn't get the channel member ». Is there other reasons for this message display?

**Comment by lfbrock** [comment] 2016-04-22 19:49
HI @GuillaumeAmat - I think that error message shows up when the site tries to access the channel members list and can't, are there any other reproducible cases where you are seeing it show up?

**Comment by lfbrock** [comment] 2016-04-22 19:54
As for the last member of a private group - it may be somewhat fixed by a future change that is planned, where we let people "Close" channels and have them show up in a "More" menu so they can be rejoined. (Basically like the Direct Messages list). 

In the meantime, we had an old ticket to hide "leave" for the last member of the channel so they only have the option to delete it. Alternatively we could change the dropdown option to be "Leave & Delete" for the last person in a private group. If someone is interested in working on a pull request to fix this I can reopen the ticket. 

https://mattermost.atlassian.net/browse/PLT-903

**Comment by GuillaumeAmat** [comment] 2016-04-25 10:58
@lfbrock I'm afraid not... That's why I'm asking here for help.
I use a Mattermost instance which contains several users, channels, private groups, etc. With deleted groups, channels, uers, etc. I refresh the page, wait, and the message appears.

**Comment by lfbrock** [comment] 2016-04-26 18:53
Thanks, we're trying to get repro steps for the "We couldn't get the channel member" but also having trouble finding a way to consistently reproduce it. If anyone else has repro steps, please feel free to comment them here

**Comment by GuillaumeAmat** [comment] 2016-04-26 19:02
If I want to check for private groups without members as reported by @norganna, where can I start to watch?

**Comment by it33** [comment] 2016-04-26 21:33
@GuillaumeAmat we're not able to reproduce what you're describing, may I ask if you manually changed the database to delete any of the items you mentioned?

**Comment by GuillaumeAmat** [comment] 2016-04-26 22:08
@it33 No we didn't. But I plan to check in the database if we have this sort of zombie groups.

**Comment by GuillaumeAmat** [comment] 2016-05-06 15:28
Ok so I checked the database and, as far as I can tell, all the channels (from the Channels table) have members related on in the ChannelMembers table.

@it33 Can you point me to another check in order to continue the investigation? Thanks!

**Comment by lfbrock** [comment] 2016-05-13 20:11
@GuillaumeAmat can you paste the SQL query for what you did? 

We've also removed the option to "Leave" for the last member of a private group, but the fix won't be in until v3.1 next month. https://github.com/mattermost/platform/pull/2888

**Closed** 2016-05-20 20:01 UTC
