### ISSUE TITLE
[Help Wanted] Joining a channel via permalink incorrectly triggers unread

### ISSUE THREAD

**Issue by it33** [mattermost/platform#4866] opened 2016-12-21 15:55 UTC
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

---

#### Summary
Joining a channel via permalink incorrectly triggers unread

#### Steps to reproduce
1. Click on a permalink to a post in a Channel X to which you are not a member--you should be added to the channel to see the post. 
2. Switch to another channel and refresh the browser

#### Observed behavior
- Channel X shows an unread message

#### Expected behavior
- Channel X should not show an unread message

**Comment by jasonblais** [comment] 2017-01-04 22:21
Closing as cannot reproduce

**Closed by jasonblais** 2017-01-04 22:21 UTC
Labels: Difficulty: Introductory, Hackfest, ReactJS
