### ISSUE TITLE
[Help Wanted] [PLT-6216] Emoji picker shifts to the left when scrolling diagonally up-left on touch pad

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6297] opened 2017-05-02 16:10 UTC
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6216)

Reproduced on Windows10/Chrome and Mac/Desktop App

1. Go to Account Settings > Advanced > Preview pre-release features and select Enable emoji picker in message input box
2. Open emoji picker in the center panel message input box
3. Scroll down using touch pad, then move diagonally up-left rather than straight up.

Expected behavior: Emoji picker scrolls up

Observed behavior: Emoji picker scrolls up but shifts to the left

**Comment by saturninoabril** [comment] 2017-06-07 00:06
Could not reproduce this issue atleast on Mac and Ubuntu with Chrome, Firefox and Safari.
Request to close this issue and just reopen if occur in the future.

**Closed** 2017-06-07 00:08 UTC
Labels: Difficulty: Introductory, ReactJS
