### ISSUE TITLE
Accepting Pull Requests: Clicking "Get Public Link" doesn't do anything

### ISSUE THREAD

**Issue by apaatsio** [mattermost/platform#908] opened 2015-10-02 12:18 UTC
Steps:
1. Upload image to channel.
2. Click image
3. Click Get Public Link

Observed result:
Nothing happens

Expected result:
I expect to see a public URL for the image.

![screenshot from 2015-10-02 15-09-28](https://cloud.githubusercontent.com/assets/195210/10246265/5948268e-6918-11e5-9708-e6e1e2b056ef.png)

**Comment by it33** [comment] 2015-10-02 12:29
Thanks @apaatsio, looks like a regression, thanks for finding it!

**Comment by it33** [comment] 2015-10-03 12:52
If anyone can figure out what broke, we'd love a pull request. This is on our list to fix as well, just want to open this up,

**Comment by coreyhulen** [comment] 2015-10-08 22:26
Fixed in master

**Closed by coreyhulen** 2015-10-08 22:26 UTC

**Comment by it33** [comment] 2015-10-08 22:36
https://github.com/mattermost/platform/pull/929
