### ISSUE TITLE
Mattermost 3.0: New Incoming Webhook UI missing private channels

### ISSUE THREAD

**Issue by qrsty** [mattermost/platform#3025] opened 2016-05-17 14:33 UTC
#### Summary
The new [integrations UI](https://mattermost.atlassian.net/browse/PLT-2698) is missing the ability to add private channels for incoming webhooks.

#### Steps to reproduce
1. Go to the Incoming Webhooks UI
2. Attempt to create a webhook for a private group/channel
3. See that only public channels are available

#### Expected behavior
I'm expecting a full list of public channels and private channels the user has access to.

#### Observed behavior
[The UI](http://i.imgur.com/IiEubI5.png) is missing any private channels we have.

The user account is a system admin.

**Comment by qrsty** [comment] 2016-05-17 15:46
The issue is present in 3.0.0 and 3.0.1.

**Comment by lfbrock** [comment] 2016-05-18 15:13
Thanks @qrsty, I filed a ticket here to track the issue: https://mattermost.atlassian.net/browse/PLT-2989

**Comment by lfbrock** [comment] 2016-05-18 17:10
Closing this issue + will track in Jira

**Closed by lfbrock** 2016-05-18 17:10 UTC

**Comment by nnewman** [comment] 2016-05-21 21:14
@lfbrock can confirm this is still an issue in 3.0.2 and is a duplicate of my earlier issue #2928
