### ISSUE TITLE
Slack Import not working

### ISSUE THREAD

**Issue by Catscrash** [mattermost/platform#5528] opened 2017-02-25 08:48 UTC
#### Summary
The Slack import tool appears to do basically nothing

#### Steps to reproduce
Version 3.6.2, Export from Slack, Import into new Team.

#### Observed behavior
I did an export using slack and imported it into the new team useing Team Settings -> Import.
Only the user slackimportuser_.... gets imported to the team and the channels are being created. No users get imported, no posts get imported, nothing.

I attached the MattermostImportSummary.txt. The usernames have been replaced by xxx,yyy, etc.

Since I believe that everything else fails, because the user import fails, I took the users.json out of the export-zip file and deleted everything but one user and uploaded it as well (replaced name with XXX again)

I had to rename it to users.txt

[users.txt](https://github.com/mattermost/platform/files/801036/users.txt)

[MattermostImportSummary.txt](https://github.com/mattermost/platform/files/801033/MattermostImportSummary.txt)

Thanks for any help

**Comment by grundleborg** [comment] 2017-02-27 08:30
Hi @Catscrash . Thanks for reporting this bug. From the description of the problem and the data in `users.txt` you have attached, it looks like you are hitting this bug: https://mattermost.atlassian.net/browse/PLT-5479

I am working on a fix for this now, which will be part of the 3.7 release of Mattermost on 16th March. If you want a workaround in the meantime, you can add an `email` field within the `profile` map of each user in `users.json`. This should enable the importer to work again in Mattermost 3.6.

**Comment by Catscrash** [comment] 2017-02-27 08:37
I see,

thanks for the info!

**Comment by jasonblais** [comment] 2017-03-02 14:45
This should be fixed with #5597, thanks @Catscrash and @grundleborg!

**Closed by jasonblais** 2017-03-02 14:45 UTC

**Comment by tcutts** [comment] 2017-08-25 13:55
I just tried importing a slack export into Mattermost 4.1 and hit exactly the same problem, although I don't think it's the same bug.  Only the slack importer user is created and added to the team, and the report just says:

`Mattermost Slack Import Log

Users created:
===============

The Integration/Slack Bot user with email slackimportuser_nwjzkrkazpf8prhsf1s7t1mwcc@localhost and password nkjkpuipc7b57gpm6f5iwydk8h has been imported.

Channels added:
=================


Notes:
=======

- Some messages may not have been imported because they were not supported by this importer.
- Slack bot messages are currently not supported.
- Additional errors may be found in the server logs.
`

Nothing appears in the mattermost log files at all?

**Comment by grundleborg** [comment] 2017-08-25 14:02
@tcutts please could you open a new ticket with your report in it? Also, if possible, (and removing any sensitive private data), could you attach either a copy of a Slack export zip file with which you can reproduce the issue, or if you can't do that, the contents of the `channels.json` and `users.json` files from within a Slack export zip file, with any private data redacted? That will allow me to investigate what is going wrong.

**Comment by tcutts** [comment] 2017-08-25 15:46
Sure – sorry.  I think I know what the cause of the problem is and the bug, if any, is just that the import tool doesn’t log that it’s experiencing problems.

 

Tim

**Comment by tcutts** [comment] 2017-08-29 21:19
I will open a new ticket, but it's not closely related to this one, and I know what the issue is.

**Comment by vickyfdk** [comment] 2019-01-03 05:55
> 
> 
> @tcutts please could you open a new ticket with your report in it? Also, if possible, (and removing any sensitive private data), could you attach either a copy of a Slack export zip file with which you can reproduce the issue, or if you can't do that, the contents of the `channels.json` and `users.json` files from within a Slack export zip file, with any private data redacted? That will allow me to investigate what is going wrong.

Hi @tcutts I have been facing same issue like:
- Some messages may not have been imported because they were not supported by this importer.
- Slack bot messages are currently not supported.
- Additional errors may be found in the server logs.

If you have found the issue please explain a little what is the exact cause of this mess.
Thanks in advance. 
Gursharan.!!
