### ISSUE TITLE
[Help Wanted] [PLT-5314] Can't use mouse to select from emoji auto-complete

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#5370] opened 2017-02-11 22:45 UTC
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5314)

Repro'd on `master`, Windows, Chrome

Can't use mouse to select from emoji auto-complete

Repro steps:
1. In the message input box, type `+:dol`
2. Try to use your mouse to select `:dolphin:`

Observed:
Using the mouse to select doesn't work.  Tabbing will select the closest match to what you have typed.

Expected:
Able to use the mouse to select from the auto-complete menu

NOTE: Probably related to #5371

**Comment by aautio** [comment] 2017-02-28 20:06
Just writing here as a note: I can't reproduce this with Apple + Chrome. For me the mouse selection from the list of emojis is working as expected.

**Comment by jasonblais** [comment] 2017-03-19 17:29
This should be fixed now

**Closed by jasonblais** 2017-03-19 17:29 UTC
