### ISSUE TITLE
Bug: "Go back to team site" link broken on "Sorry, we could not find this page" error page

### ISSUE THREAD

**Issue by rompic** [mattermost/platform#1394] opened 2015-11-11 09:22 UTC
i just mistyped /admine_console and got the "... needs your help" page.
The go back to teamsite link links to the same wrong page /admine_console again

**Comment by it33** [comment] 2015-11-12 05:26
Repro confirmed, ticket filed: https://mattermost.atlassian.net/browse/PLT-1129

**Comment by it33** [comment] 2016-02-21 03:24
Closing since this is tracked in Jira ticket now

**Closed by it33** 2016-02-21 03:24 UTC
