### ISSUE TITLE
Does not work with GNOME Web

### ISSUE THREAD

**Issue by bochecha** [mattermost/platform#3542] opened 2016-07-11 06:40 UTC
I'm using framateam.org which is running Mattermost 3.1.0

If I try running it in GNOME Web (aka Epiphany), I get a redirection error (Too many redirects)

Looking at the URL, I can see that even though I tried opening https://framateam.org , I was redirected to https://framateam.org/error?title=Framateam+needs+your+help%3A&message=Your+current+browser+is+not+supported%2C+please+upgrade+to+one+of+the+following+browsers%3A+Google+Chrome+21+or+higher%2C+Internet+Explorer+11+or+higher%2C+FireFox+14+or+higher%2C+Safari+9+or+higher&details=&link=%2F&linkmessage=Go+back+to+Mattermost , which in turn seems to redirect to itself.

So I guess there are two problems:

* the error page redirects to itself, putting the browser in a redirection loop
* Mattermost refuses to work with GNOME Web

And that second one is what I'd really like to see fixed.

> Your current browser is not supported, please upgrade to one of the following browsers: Google Chrome 21 or higher, Internet Explorer 11 or higher, FireFox 14 or higher, Safari 9 or higher

I'm running [GNOME Web 3.20](https://wiki.gnome.org/Apps/Web), which is based on [WebKitGtk 2.12.3](https://webkitgtk.org/).

Mattermost claims to run with Safari 9, the latest version of Safari, which should be very similar to GNOME Web, since they are both based on recent versions of WebKit.

Can GNOME Web be added to the list of supported browsers?

I'm guessing the problem is in this function: https://github.com/mattermost/platform/blob/2e5617c29be69637acd384e85f795a0b343bec8d/web/web.go#L43-L57

**Comment by mcatanzaro** [comment] 2016-07-11 13:36
It works if you replace Version/8.0 with Version/9.0 in the user agent. The problem is that function explicitly blacklists Safari 8, but WebKitGTK+ pretends to be Safari 8 for compatibility with other sites. This is the first time I've seen a Safari UA blacklisted before. We should change this to Version/9.0 in WebKit trunk, since trunk is obviously much more similar to Safari 9 than to Safari 8, but that change will inevitably break some unknown sites, so it's too risky to backport to WebKitGTK+ 2.12. Anyway, that's already done in https://bugs.webkit.org/show_bug.cgi?id=142074, I just need to get back to working on that patch.

UA testing is basically impossible to get right, because web engines have no choice but to fake UAs to pass your UA tests. The only correct solution is to do proper feature tests and not check the UA at all. It's just going to break again in the future when you decide to blacklist Safari 9 before we update the WebKitGTK+ UA. But if you insist on retaining the UA testing, you should check the AppleWebKit version (e.g. AppleWebKit/602.1) rather than the Safari version (e.g. Version/8.0). The AppleWebKit version gets updated automatically by Apple and is relatively accurate at indicating Safari compatibility, but the Safari version gets incremented manually at random times.

**Comment by jasonblais** [comment] 2016-07-12 21:30
Thanks @bochecha for the report, and @mcatanzaro for the swift reply,

To answer your questions, @bochecha:

1) we have a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-959) to improve our 'unsupported browser page'. The plan is to add a link to download compatible browser versions with Mattermost.

2) if you'd like GNOME Web added to the list of supported browsers, can I have your help contributing your suggestion in the [feature idea forum](https://mattermost.uservoice.com/forums/306457-general) so it can be discussed, upvoted and considered for a ticket accepting pull requests? 

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get 10 votes in the feature idea forum, and each one influences the future of the project.

**Comment by bochecha** [comment] 2016-07-12 23:17
> 2) if you'd like GNOME Web added to the list of supported browsers, ...

I don't think I want to have GNOME Web added to the list of supported browsers, if that means adding it to a whitelist based on user-agent.

As @mcatanzaro (and in case that wasn't clear, he is an upstream WebKit developer) explained, you should test feature availability, not the user agent.

Otherwise, you'll always have to add new, obscure browsers to that UA-based whitelist as they appear and implement the features you need.

Worse, if you advertise a browser as supported, then you'll need to test it regularly, to remove it from the « supported browsers » list if it doesn't work any more in the future.

If instead you just test for the features you need, then telling the user whether their browser is supported or not is done dynamically, removing the need for you to maintain that list.

---

However, I just found that this had already been reported: https://github.com/mattermost/platform/issues/3353#event-703118004

Sorry for not searching better before opening a duplicate.

In any case, the feature idea was already submitted on your forum: https://mattermost.uservoice.com/forums/306457-general/suggestions/15011652-stop-sniffing-the-user-agent-use-feature-detectio

This really is what should be done.

Please? :smiley:

**Comment by jasonblais** [comment] 2016-07-14 19:48
Thanks @bochecha and sorry for my misunderstanding.

If you'd like to add more feedback in the [Feature Idea forum post](https://mattermost.uservoice.com/forums/306457-general/suggestions/15011652-stop-sniffing-the-user-agent-use-feature-detectio), you're welcome to do so. In the meantime, propose closing this issue and tracking the feature idea for now instead

**Comment by jasonblais** [comment] 2016-07-17 18:09
Thanks again @bochecha,

closing the issue for now, but I encourage you to participate in [the Feature Idea forum post](https://mattermost.uservoice.com/forums/306457-general/suggestions/15011652-stop-sniffing-the-user-agent-use-feature-detectio) for further discussion.

**Closed by jasonblais** 2016-07-17 18:09 UTC
Labels: Awaiting Submitter Action
