### ISSUE TITLE
"Jump" from search results, not working on Mac desktop app

### ISSUE THREAD

**Issue by devarshi112** [mattermost/platform#6988] opened 2017-07-19 23:59 UTC
Clicking on "Load more messages" doesn't do anything on Mac app when viewing previous messages.

Reproduced this on multiple environments/machines.

Version 3.7.0 (3.7.0.3.7.0)

**Comment by jasonblais** [comment] 2017-07-20 00:26
@devarshi112 

Which Mattermost server version is this on? You can find it from the Main Menu > About Mattermost.

![image](https://user-images.githubusercontent.com/13119842/28395227-79e3597e-6cc0-11e7-8138-57cd3e50285b.png)

Also, can you try if
 - it works on Chrome (or another browser)
 - View > Clear Cache and Reload fixes the issue
 - quitting, then re-opening the app fixes the issue

**Comment by devarshi112** [comment] 2017-07-20 00:32
My responses: 
* Version: Version 3.7.0 (3.7.0.3.7.0)
* it works on Chrome (or another browser): No
* View > Clear Cache and Reload fixes the issue: No
* quitting, then re-opening the app fixes the issue: No

**Comment by jasonblais** [comment] 2017-07-20 00:37
Got it, I thought the version number was for the desktop app.

Can you try upgrading to the latest Mattermost version to see if the issue is resolved? You can download it here https://about.mattermost.com/download/

**Comment by devarshi112** [comment] 2017-07-21 19:05
How to know the version number of the desktop app? Also, do I need to upgrade the Mattermost server? I am using Mattermost inside an organization and don't have permissions listed in https://docs.mattermost.com/administration/upgrade.html#before-you-begin

**Comment by jasonblais** [comment] 2017-07-22 03:18
You can find the version of the Desktop App from the "Help" menu.

Yes, you're administrator would need to upgrade the Mattermost version. We'd recommend it as the post area had a lot of improvements and might fix the issue you're experiencing. There are also some security updates so upgrading is recommended.

**Comment by lindy65** [comment] 2017-08-02 08:38
Hi @devarshi112,

Circling back to find out whether your issue was resolved by your administrator upgrading to the latest Mattermost version?

**Comment by devarshi112** [comment] 2017-08-04 23:15
We upgraded to version 4.0 and I am not sure if it resolves the issue. In the previous version there were two links to "Load more messages" - one on the top and the other at the bottom and both didn't work. 

In the new version though, there is only one link to "Load more messages" at the top, and it works. The bottom one is not present and on scrolling down, the messages stop appearing after a point and the link to "jump to recent messages" appears which when clicked takes us to the most recent messages thus breaking the continuity of messages. 

So I believe I would really wish the bottom "Load more messages" link was retained and working in the new version.

**Comment by devarshi112** [comment] 2017-08-04 23:17
To be precise, we upgraded to version 4.0.1

**Comment by lindy65** [comment] 2017-08-14 19:08
Hi @devarshi112 

Thanks for your feedback,

Are you referring to the two areas I've highlighted in red on the screenshot below?

![image](https://user-images.githubusercontent.com/13020833/29286749-5af29f48-8133-11e7-9d94-2801517e4a3c.png)

I believe the only time "jump to recent messages" is displayed is when you've "jumped" to a message from a search result.

![image](https://user-images.githubusercontent.com/13020833/29287044-67609acc-8134-11e7-92d1-0db437794e01.png)

Is the above perhaps what you're describing?

**Comment by devarshi112** [comment] 2017-08-23 05:23
I was talking about the second screenshot where we jump to a message from a search result.

**Comment by lindy65** [comment] 2017-08-23 07:26
Thanks for the feedback @devarshi112,

I'll ask one of my team mates with a Mac to test your issue and see if they can reproduce it.

**Comment by lindy65** [comment] 2017-08-23 17:24
Hi @devarshi112,

I found [this Jira ticket](https://mattermost.atlassian.net/browse/PLT-7416) that could be what's causing your issue.  

Can you test to see if `jump` works when clicking on the first search result and breaks thereafter - or - does `jump` from search results not work for you at all?

**Comment by devarshi112** [comment] 2017-08-29 00:09
You are not understanding the issue correctly. 

I want the "Load more messages" to be present at the bottom as well. The "Click here to jump to recent messages" breaks the continuity of messages and takes us to the most recent message. Use case: 
1. Search for a message and "jump" to that message.
2. After a few messages in that sequence, the link to "Click here to jump to recent messages" appears which breaks the continuity of messages.

**Comment by lindy65** [comment] 2017-08-29 06:59
Hi @devarshi112,

Thank you for your feedback and for explaining exactly what it is you're requesting.  You're correct - I was not understanding your issue!  Apologies.

It was by design that "Click here to jump to recent messages" takes you to new messages in the channel and doesn't just continue to scroll through all the messages below the message you "jumped" to from search results.  

This is because the message you "jumped" to could be from a couple of months ago and would have many messages below it to scroll through.

If this is a feature you'd find useful, perhaps consider creating a [feature suggestion](https://mattermost.uservoice.com/forums/306457-general) on our forum.  As it stands at present, what you're describing isn't a bug but rather a code change.

I hope this helps?

**Closed** 2017-08-30 08:11 UTC
